### ISSUE TITLE
Chinese character in the path using netcdf4 dataset

### ISSUE THREAD

**Issue by LiNinghui-AI** [Unidata/netcdf4-python#997] opened 2020-02-29 11:43 UTC
I need to open a nc file with netcdf4. But in the path of the file, there are chinese characters and netCDF4.Dataset return the error : "No such file or directory". But if I use "os.path.isfile", the file is found. I've tried to decode, encode (in utf-8) the path without result.

Is there any option to use in dataset call ?

Thanks.

**Comment by jswhit2** [comment] 2020-03-02 21:36
This may be related to https://github.com/Unidata/netcdf4-python/issues/941, which in turn is related to HDF5 unicode filename support (https://forum.hdfgroup.org/t/non-english-characters-in-hdf5-file-name/4627/8)

**Comment by jswhit2** [comment] 2020-03-02 21:38
https://github.com/h5py/h5py/issues/839 suggests that this may be been fixed in HD5 1.10.6 (at least for windows).  What version of HDF5 are you using?

**Comment by jswhit2** [comment] 2020-03-02 22:18
The following works for me 

```python
import netCDF4
filename="delta_\u0394.nc"
print(filename)
nc = netCDF4.Dataset(filename,'w')
nc.filename = filename
nc.close()
nc = netCDF4.Dataset(filename)
print(nc)

delta_Δ.nc
<class 'netCDF4._netCDF4.Dataset'>
root group (NETCDF4 data model, file format HDF5):
    filename: delta_Δ.nc
    dimensions(sizes):
    variables(dimensions):
    groups:
```

**Comment by LiNinghui-AI** [comment] 2020-03-03 03:28
> The following works for me
> 
> ```python
> import netCDF4
> filename="delta_\u0394.nc"
> print(filename)
> nc = netCDF4.Dataset(filename,'w')
> nc.filename = filename
> nc.close()
> nc = netCDF4.Dataset(filename)
> print(nc)
> 
> delta_Δ.nc
> <class 'netCDF4._netCDF4.Dataset'>
> root group (NETCDF4 data model, file format HDF5):
>     filename: delta_Δ.nc
>     dimensions(sizes):
>     variables(dimensions):
>     groups:
> ```
> 
> Can you modify this example to use the utf-8 filename causing you problems?

Thank you very much! I am going to try.

**Comment by LiNinghui-AI** [comment] 2020-03-03 03:29
> The following works for me
> 
> ```python
> import netCDF4
> filename="delta_\u0394.nc"
> print(filename)
> nc = netCDF4.Dataset(filename,'w')
> nc.filename = filename
> nc.close()
> nc = netCDF4.Dataset(filename)
> print(nc)
> 
> delta_Δ.nc
> <class 'netCDF4._netCDF4.Dataset'>
> root group (NETCDF4 data model, file format HDF5):
>     filename: delta_Δ.nc
>     dimensions(sizes):
>     variables(dimensions):
>     groups:
> ```
> 
> Can you modify this examptf-8 filename causing you problems?

**Comment by LiNinghui-AI** [comment] 2020-03-03 03:36
> [h5py/h5py#839](https://github.com/h5py/h5py/issues/839) suggests that this may be been fixed in HD5 1.10.6 (at least for windows). What version of HDF5 are you using?

I use netCDF4 1.5.3.

**Comment by LiNinghui-AI** [comment] 2020-03-03 03:42
> The following works for me
> 
> ```python
> import netCDF4
> filename="delta_\u0394.nc"
> print(filename)
> nc = netCDF4.Dataset(filename,'w')
> nc.filename = filename
> nc.close()
> nc = netCDF4.Dataset(filename)
> print(nc)
> 
> delta_Δ.nc
> <class 'netCDF4._netCDF4.Dataset'>
> root group (NETCDF4 data model, file format HDF5):
>     filename: delta_Δ.nc
>     dimensions(sizes):
>     variables(dimensions):
>     groups:
> ```
> 
> Can you modify this example to use the utf-8 filename causing you problems?

import netCDF4 as np
from netCDF4 import Dataset
path = r"H:\LNHCourse\海洋探测技术专题实验\专题实验八\V2019151040600.L2_SNPP_OC.nc"
fh = Dataset( path )

Above is my code, I think it is simple and I met the error :
[Errno 2] No such file or directory: b'H:\\LNHCourse\\\xe6\xb5\xb7\xe6\xb4\x8b\xe6\x8e\xa2\xe6\xb5\x8b\xe6\x8a\x80\xe6\x9c\xaf\xe4\xb8\x93\xe9\xa2\x98\xe5\xae\x9e\xe9\xaa\x8c\\\xe4\xb8\x93\xe9\xa2\x98\xe5\xae\x9e\xe9\xaa\x8c\xe5\x85\xab\\V2019151040600.L2_SNPP_OC.nc'

**Comment by jswhit** [comment] 2020-03-03 15:37
What encoding are you using?

**Comment by LiNinghui-AI** [comment] 2020-03-06 07:45
> What encoding are you using?

UTF8

**Comment by jswhit** [comment] 2020-03-09 18:56
I think this is a windows filename encoding issue - I can create a file with this filename and read it back in on macos x and linux.  Unfortunately, I don't have access to Windows.

**Comment by jswhit** [comment] 2020-03-10 16:28
Disregard my last message - I can now reproduce this on macos x and linux.  Here's the script:
```python
import netCDF4, os
dirpath1 =\
b'\xe6\xb5\xb7\xe6\xb4\x8b\xe6\x8e\xa2\xe6\xb5\x8b\xe6\x8a\x80\xe6\x9c\xaf\xe4\xb8\x93\xe9\xa2\x98\xe5\xae\x9e\xe9\xaa\x8c'.decode('utf-8')
dirpath2 =\
b'\xe4\xb8\x93\xe9\xa2\x98\xe5\xae\x9e\xe9\xaa\x8c\xe5\x85\xab'.decode('utf-8')
dirpath = os.path.join(dirpath1,dirpath2)
os.makedirs(dirpath,exist_ok=True)
filename=os.path.join(dirpath,'V2019151040600.L2_SNPP_OC.nc')
print(filename)
nc = netCDF4.Dataset(filename,'w')
nc.filename = filename
nc.close()
nc = netCDF4.Dataset(filename)
print(nc.filename)
```
which produces

[mac28:~/python] jwhitaker% python3.7 unicode_filename.py
海洋探测技术专题实验/专题实验八/V2019151040600.L2_SNPP_OC.nc
Traceback (most recent call last):
  File "unicode_filename.py", line 10, in <module>
    nc = netCDF4.Dataset(filename,'w')
  File "netCDF4/_netCDF4.pyx", line 2321, in netCDF4._netCDF4.Dataset.__init__
  File "netCDF4/_netCDF4.pyx", line 1885, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'\xe6\xb5\xb7\xe6\xb4\x8b\xe6\x8e\xa2\xe6\xb5\x8b\xe6\x8a\x80\xe6\x9c\xaf\xe4\xb8\x93\xe9\xa2\x98\xe5\xae\x9e\xe9\xaa\x8c/\xe4\xb8\x93\xe9\xa2\x98\xe5\xae\x9e\xe9\xaa\x8c\xe5\x85\xab/V2019151040600.L2_SNPP_OC.nc'

**Comment by jswhit** [comment] 2020-03-10 16:36
The following h5py script works, so I don't think this is an hdf5 issue

```python
import h5py, os
dirpath1 =\
b'\xe6\xb5\xb7\xe6\xb4\x8b\xe6\x8e\xa2\xe6\xb5\x8b\xe6\x8a\x80\xe6\x9c\xaf\xe4\xb8\x93\xe9\xa2\x98\xe5\xae\x9e\xe9\xaa\x8c'.decode('utf-8')
dirpath2 =\
b'\xe4\xb8\x93\xe9\xa2\x98\xe5\xae\x9e\xe9\xaa\x8c\xe5\x85\xab'.decode('utf-8')
dirpath = os.path.join(dirpath1,dirpath2)
os.makedirs(dirpath,exist_ok=True)
filename=os.path.join(dirpath,'V2019151040600.L2_SNPP_OC.h5')
print(filename)
f = h5py.File(filename,'w')
dset = f.create_dataset("mydataset", (100,), dtype='i')
f.close()
f = h5py.File(filename,'r')
print(f)
```

[mac28:~/python] jwhitaker% python3.7 unicode_filename_h5py.py
海洋探测技术专题实验/专题实验八/V2019151040600.L2_SNPP_OC.h5
<HDF5 file "V2019151040600.L2_SNPP_OC.h5" (mode r)>

**Comment by jswhit** [comment] 2020-03-10 16:52
From https://support.hdfgroup.org/HDF5/doc/Advanced/UsingUnicode/index.html:

`Since file access is a system issue, filenames do not fall within the scope of HDF5’s UTF-8 capabilities; filenames are encoded at the system level. Linux and Mac OS systems normally handle UTF-8 encoded filenames correctly while Windows systems generally do not.`

A simple workaround in this case (since the chinese characters are in the directory names, not the filename itself) is to create the directory in python, change the working directory, and then create the file in that directory

```python
import netCDF4, os
dirpath1 =\
b'\xe6\xb5\xb7\xe6\xb4\x8b\xe6\x8e\xa2\xe6\xb5\x8b\xe6\x8a\x80\xe6\x9c\xaf\xe4\xb8\x93\xe9\xa2\x98\xe5\xae\x9e\xe9\xaa\x8c'.decode('utf-8')
dirpath2 =\
b'\xe4\xb8\x93\xe9\xa2\x98\xe5\xae\x9e\xe9\xaa\x8c\xe5\x85\xab'.decode('utf-8')
dirpath = os.path.join(dirpath1,dirpath2)
os.makedirs(dirpath,exist_ok=True)
os.chdir(dirpath)
filename='V2019151040600.L2_SNPP_OC.nc'
print(filename)
nc = netCDF4.Dataset(filename,'w')
nc.filename = filename
nc.close()
nc = netCDF4.Dataset(filename)
print(os.getcwd)
print(nc.filename
```

Still curious as to how h5py manages to make it work, digging further...

**Comment by LiNinghui-AI** [comment] 2020-03-11 03:48
> From https://support.hdfgroup.org/HDF5/doc/Advanced/UsingUnicode/index.html:
> 
> `Since file access is a system issue, filenames do not fall within the scope of HDF5’s UTF-8 capabilities; filenames are encoded at the system level. Linux and Mac OS systems normally handle UTF-8 encoded filenames correctly while Windows systems generally do not.`
> 
> A simple workaround in this case (since the chinese characters are in the directory names, not the filename itself) is to create the directory in python, change the working directory, and then create the file in that directory
> 
> ```python
> import netCDF4, os
> dirpath1 =\
> b'\xe6\xb5\xb7\xe6\xb4\x8b\xe6\x8e\xa2\xe6\xb5\x8b\xe6\x8a\x80\xe6\x9c\xaf\xe4\xb8\x93\xe9\xa2\x98\xe5\xae\x9e\xe9\xaa\x8c'.decode('utf-8')
> dirpath2 =\
> b'\xe4\xb8\x93\xe9\xa2\x98\xe5\xae\x9e\xe9\xaa\x8c\xe5\x85\xab'.decode('utf-8')
> dirpath = os.path.join(dirpath1,dirpath2)
> os.makedirs(dirpath,exist_ok=True)
> os.chdir(dirpath)
> filename='V2019151040600.L2_SNPP_OC.nc'
> print(filename)
> nc = netCDF4.Dataset(filename,'w')
> nc.filename = filename
> nc.close()
> nc = netCDF4.Dataset(filename)
> print(os.getcwd)
> print(nc.filename)
> ```
> 
> Still curious as to how h5py manages to make it work, digging further...
Thank you very much for your help, I followed your suggestion to successfully solve this problem

**Comment by jswhit2** [comment] 2020-03-11 13:06
A potential solution (bug fix in the C lib) is being discussed at https://github.com/Unidata/netcdf-c/issues/1666

**Closed** 2020-03-14 01:15 UTC

**Comment by zouyaoji** [comment] 2021-07-22 03:35
@LiNinghui-AI  嗨 问一下解决了吗？我这有中文路径还是不行呢~

**Comment by zgcao** [comment] 2022-01-04 08:55
I tryied an indirect method:
(1) replace the filename using English character using os.rename(src, dst);
(2) using the netcdf4 to read it.

**Comment by shengrihui** [comment] 2025-05-28 02:32
Using `encoding='gbk'` solved the issue with Chinese file paths for me.

**Comment by shengrihui** [comment] 2025-05-28 06:19
> Using `encoding='gbk'` solved the issue with Chinese file paths for me.

@jswhit2 

However, this doesn’t seem like an elegant, direct, or complete solution.
When I use xarray to read nc files, it doesn’t support an encoding parameter (so maybe I should open an issue there as well).
I also wonder whether the underlying C implementation might be using something like fopen, which doesn’t support wide characters, causing this issue. File encodings are quite tricky for me, and I’m not really familiar with them.

**Comment by DennisHeimbigner** [comment] 2025-05-28 20:29
The file docs/FAQ.md in the netcdf-c package says this:
````
Starting with Windows 10 build 17134, Windows can support use of
the UTF-8 character set. We strongly encourage Windows users to
enable this feature. This requires the following steps.

1. In the "run" toolbar, execute the command "intl.cpl".
2. Move to the Administrative tab.
3. Move to "Change system locale"
4. Check the box at the bottom labeled something like
"Beta: Use Unicode UTF-8 for worldwide language support"
````

**Comment by shengrihui** [comment] 2025-05-29 01:01
> The file docs/FAQ.md in the netcdf-c package says this:
> 
> ```
> Starting with Windows 10 build 17134, Windows can support use of
> the UTF-8 character set. We strongly encourage Windows users to
> enable this feature. This requires the following steps.
> 
> 1. In the "run" toolbar, execute the command "intl.cpl".
> 2. Move to the Administrative tab.
> 3. Move to "Change system locale"
> 4. Check the box at the bottom labeled something like
> "Beta: Use Unicode UTF-8 for worldwide language support"
> ```

Amazing~ 
This is a solution! 
Thank you for your reply!
