### ISSUE TITLE
num2date returning incorrect values

### ISSUE THREAD

**Issue by dariuspbom** [Unidata/netcdf4-python#330] opened 2015-02-12 00:28 UTC
num2date appears to be returning incorrect values frequently off by one.

Underlying lib is netcdf-4.3.2.  Python netCDF4 versions 1.1.2 and 1.1.3 appear to be affected.  Version 1.1.1 is good.

Demonstrated with the following:

>>> import netcdftime
>>> t = netcdftime.utime("seconds since 1970-01-01T00:00:00Z")
>>> for n in xrange(60):
...     print n, t.num2date(n), int(round(t.date2num(t.num2date(n))))
... 
0 1970-01-01 00:00:00 0
1 1970-01-01 00:00:00 0
2 1970-01-01 00:00:01 1
3 1970-01-01 00:00:02 2
4 1970-01-01 00:00:04 4
5 1970-01-01 00:00:05 5
6 1970-01-01 00:00:06 6
7 1970-01-01 00:00:07 7
8 1970-01-01 00:00:07 7
9 1970-01-01 00:00:08 8
10 1970-01-01 00:00:09 9
11 1970-01-01 00:00:10 10
12 1970-01-01 00:00:12 12
13 1970-01-01 00:00:13 13
14 1970-01-01 00:00:14 14
15 1970-01-01 00:00:14 14
16 1970-01-01 00:00:15 15
17 1970-01-01 00:00:16 16
18 1970-01-01 00:00:17 17
19 1970-01-01 00:00:19 19
20 1970-01-01 00:00:20 20

Only up to 20 shown, but you can see that number 1, 2, 3, 8, 9, 10, 11, 15, 16, 17, 18 all get converted to a date with num2date incorrectly.

With version 1.1.1 the output is good:

>>> import netcdftime
>>> t = netcdftime.utime("seconds since 1970-01-01T00:00:00Z")
>>> for n in xrange(60):
...     print n, t.num2date(n), int(round(t.date2num(t.num2date(n))))
... 
0 1970-01-01 00:00:00 0
1 1970-01-01 00:00:01 1
2 1970-01-01 00:00:02 2
3 1970-01-01 00:00:03 3
4 1970-01-01 00:00:04 4
5 1970-01-01 00:00:05 5
6 1970-01-01 00:00:06 6
7 1970-01-01 00:00:07 7
8 1970-01-01 00:00:08 8
9 1970-01-01 00:00:09 9
10 1970-01-01 00:00:10 10
11 1970-01-01 00:00:11 11
12 1970-01-01 00:00:12 12
13 1970-01-01 00:00:13 13
14 1970-01-01 00:00:14 14
15 1970-01-01 00:00:15 15
16 1970-01-01 00:00:16 16
17 1970-01-01 00:00:17 17
18 1970-01-01 00:00:18 18
19 1970-01-01 00:00:19 19
20 1970-01-01 00:00:20 20

Here all the conversions look good both with num2date and back with num2date.

**Comment by jswhit** [comment] 2015-02-16 15:36
@cpaulik   could you have a look at this?  It may be related to your optimization of netcdftime (issue #296)

**Comment by jswhit** [comment] 2015-02-16 16:01
Tentative fix for this in issue330 branch.  This is a pretty serious bug, so we should push a new release ASAP.

**Comment by cpaulik** [comment] 2015-02-16 16:19
Yes,

The problem is that microseconds are not used in date2num, and also not in the custom datetime class.
For now your fix to limit ourselves to second accuracy should work fine. 

I can work on a more comprehensive fix later today.

**Comment by jswhit** [comment] 2015-02-16 18:58
I guess I'd rather not even provide microseconds, if we can't guarantee accuracy.  Right now the docs state that the results are only accurate to the second.

**Comment by cpaulik** [comment] 2015-02-17 00:22
I agree. Microsecond accuracy on a roundtrip conversion is rather difficult. Seconds should be fine for a lot of applications.

If we would want to go to microseconds, I think we have to check everything in detail.

**Comment by jswhit** [comment] 2015-02-17 01:39
Fixed by merging pull request #334

**Closed by jswhit** 2015-02-17 01:39 UTC
