### ISSUE TITLE
Issues with NumPy 2.0?

### ISSUE THREAD

**Issue by mgrover1** [Unidata/netcdf4-python#1338] opened 2024-06-17 17:01 UTC
Version: netCDF4-1.6.5
Environmental information: Mac, Linux, Windows

When building wheels for Py-ART, which relies on netCDF4-python, we run into the following error

```python
  src/netCDF4/_netCDF4.pyx:1: in init netCDF4._netCDF4
      ???
  E   ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```

This error appears every time netCDF is imported.

This can be reproduced by installing NumPy 2.0, building wheels, and running tests.

I included links to the failing CI system
- https://github.com/ARM-DOE/pyart/actions/runs/9545161074/job/26317694606?pr=1596

As well as the failing builds on the netcdf4-python side (failing as of 10 hours ago)
https://github.com/Unidata/netcdf4-python/actions/runs/9542919364

Any suggestions how this could be resolved?

**Comment by ocefpaf** [comment] 2024-06-17 17:11
Building with numpy 2.0 was possible since https://github.com/Unidata/netcdf4-python/commit/1f2b711eb8ec90a0fd2d6b96cf34ac5c0bba5711 and the only release that got built against it was https://github.com/Unidata/netcdf4-python/releases/tag/v1.7.0rel. I don't think it will be possible to do what you want unless you download the sdist for 1.6.5, patch it for numpy 2.0, and build it from the patched source. Can you upgrade to 1.7.0 instead?

**Comment by mgrover1** [comment] 2024-06-17 17:15
Thanks for the info here - I will try upgrading and see if that resolves the issue.

**Comment by mgrover1** [comment] 2024-06-17 17:28
The CI system claims that netcdf4-python 1.7.0 cannot be found
https://github.com/ARM-DOE/pyart/actions/runs/9551985254/job/26327550225?pr=1596#step:5:1494

**Comment by ocefpaf** [comment] 2024-06-17 17:35
I would need to look into your CI config but it works for me:

```
pip install numpy==2 "netcdf4>=1.7.0"
```

```
Collecting numpy==2
  Using cached numpy-2.0.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (60 kB)
Collecting netcdf4>=1.7.0
  Using cached netCDF4-1.7.0-cp39-cp39-manylinux_2_28_x86_64.whl.metadata (1.8 kB)
Collecting cftime (from netcdf4>=1.7.0)
  Using cached cftime-1.6.4-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (8.7 kB)
Collecting certifi (from netcdf4>=1.7.0)
  Using cached certifi-2024.6.2-py3-none-any.whl.metadata (2.2 kB)
Using cached numpy-2.0.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (19.3 MB)
Using cached netCDF4-1.7.0-cp39-cp39-manylinux_2_28_x86_64.whl (9.7 MB)
Using cached certifi-2024.6.2-py3-none-any.whl (164 kB)
Using cached cftime-1.6.4-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.3 MB)
Installing collected packages: numpy, certifi, cftime, netcdf4
Successfully installed certifi-2024.6.2 cftime-1.6.4 netcdf4-1.7.0 numpy-2.0.0
```

**Comment by mgrover1** [comment] 2024-06-17 17:37
We are using cibuildwheel here, here is a link to the associated action
https://github.com/ARM-DOE/pyart/blob/main/.github/workflows/wheels.yml

**Comment by ocefpaf** [comment] 2024-06-17 17:40
> We are using cibuildwheel here, here is a link to the associated action https://github.com/ARM-DOE/pyart/blob/main/.github/workflows/wheels.yml

Ah, reading the whole error message it seems that the problem is:

```
INFO: pip is looking at multiple versions of arm-pyart to determine which version is compatible with other requirements. This could take a while.
  ERROR: Could not find a version that satisfies the requirement netCDF4>=1.7.0 (from arm-pyart) (from versions: 1.5.4, 1.5.5, 1.5.5.1, 1.5.6, 1.5.7, 1.5.8, 1.6.0, 1.6.1, 1.6.2, 1.6.3, 1.6.4, 1.6.5)
```

Something else is holding you from upgrading to netcdf4 >=1.7.0. That is why you ended up with 1.6.5 in the first place even though you did not pin to it. You will need to look into your dependency chain to figure this out.

**Comment by mgrover1** [comment] 2024-06-17 17:41
Sounds good - do you have an estimate as to when the conda-forge release of 1.7.0 will be available?

**Comment by ocefpaf** [comment] 2024-06-17 17:45
> Sounds good - do you have an estimate as to when the conda-forge release of 1.7.0 will be available?

It won't, we will skip that one due to https://github.com/Unidata/netcdf4-python/issues/1329.

You can use 1.6.5 from conda-forge with numpy 2.0 though b/c conda does allow for repo data patches and quick rebuilds of old tags. The `netcdf4 1.6.5` build number 2 from conda-forge is already compatible with numpy 2.0.

**Comment by mgrover1** [comment] 2024-06-17 17:55
wonderful! Thank you - I will look into the upstream packages.

**Comment by ocefpaf** [comment] 2024-06-17 18:07
Closing this one b/c it is not an issue we can solve here. Please reopen if you disagree.

**Closed by ocefpaf** 2024-06-17 18:07 UTC

**Comment by veenstrajelmer** [comment] 2024-10-11 21:09
Could it not be that the dependency resolver excludes rel/post releases? Since the normal 1.7.* are all yanked, so it could makes sense that the resolver only shows releases up to 1.6.5. In that case this issue can be resolved by releasing another netcdf4 release.
