### ISSUE TITLE
Enum types issues

### ISSUE THREAD

**Issue by pgamez** [Unidata/netcdf4-python#775] opened 2018-03-09 08:51 UTC
Hi,
I've noticed an error in the name of the enum types in reading mode.
This script shows the error:
```python
from netCDF4 import Dataset

with Dataset('test.nc', 'w') as fp:
    enum = fp.createEnumType('b', 'test', {'xxx': 0})
    print(enum.name)

with Dataset('test.nc') as fp:
    enum = fp.enumtypes['test']
    print(enum.name)
```
The output is this:
```
test
xxx
```
... but it should be this:
```
test
test
```
Using netcdf4 v.1.3.1
Cheers
Pedro

**Comment by pgamez** [comment] 2018-03-09 11:27
By the way... I've just found a new issue.
I tried to copy some content from a netcdf with enum types to a new one. If the enum type doesn't appear in the first place of the list of enum types, then it will raise a RuntimeError.
You should reproduce the problem with this code. Note that `enum2` is created after `enum1`
```python
from netCDF4 import Dataset

# Example of netcdf
with Dataset('orig.nc', 'w') as orig:
    enum1 = orig.createEnumType('b', 'enum1', {'aaa': 0, 'bbb': 1})
    enum2 = orig.createEnumType('b', 'enum2', {'xxx': 0, 'yyy': 1})
    orig.createVariable('var', enum2)

# Copy the example to a new netcdf
with Dataset('orig.nc') as orig:
    enum = orig.enumtypes['enum2']
    origvar = orig.variables['var']

    with Dataset('dest.nc', 'w') as dest:
        dest.createEnumType(enum.dtype, 'enum2', enum.enum_dict)
        dest.createVariable(origvar.name, origvar.datatype, origvar.dimensions)
```
Then the execution stops:
```
$ ./test.py 
Traceback (most recent call last):
  File "./test.py", line 18, in <module>
    dest.createVariable(origvar.name, origvar.datatype, origvar.dimensions)
  File "netCDF4/_netCDF4.pyx", line 2437, in netCDF4._netCDF4.Dataset.createVariable
  File "netCDF4/_netCDF4.pyx", line 3389, in netCDF4._netCDF4.Variable.__init__
  File "netCDF4/_netCDF4.pyx", line 1638, in netCDF4._netCDF4._ensure_nc_success
RuntimeError: NetCDF: Not a valid data type or _FillValue type mismatch
```
However, there's no error when the `enum2` is created before `enum1`... So this script works:
```python
#!/usr/bin/env python3

from netCDF4 import Dataset

# Example of netcdf
with Dataset('orig.nc', 'w') as orig:
    enum2 = orig.createEnumType('b', 'enum2', {'xxx': 0, 'yyy': 1})
    enum1 = orig.createEnumType('b', 'enum1', {'aaa': 0, 'bbb': 1})
    orig.createVariable('var', enum2)

# Copy the example to a new netcdf
with Dataset('orig.nc') as orig:
    enum = orig.enumtypes['enum2']
    origvar = orig.variables['var']

    with Dataset('dest.nc', 'w') as dest:
        dest.createEnumType(enum.dtype, 'enum2', enum.enum_dict)
        dest.createVariable(origvar.name, origvar.datatype, origvar.dimensions)
```
Pedro

**Comment by jswhit** [comment] 2018-03-09 13:43
Good catch!  Fix in pull request #776

**Comment by pgamez** [comment] 2018-03-09 13:55
thanks! 
pedro

**Comment by jswhit** [comment] 2018-03-09 14:49
As for the second problem, you are try to create a variable that with a reference to an enum datatype that exists in a different file.  I think you will find that

```python
    with Dataset('dest.nc', 'w') as dest:
        enum_new = dest.createEnumType(enum.dtype, 'enum2', enum.enum_dict)
        dest.createVariable(origvar.name, enum_new, origvar.dimensions)

works

**Comment by jswhit** [comment] 2018-03-09 14:51
As you can tell, not many people have actually used the enum datatype ....

**Comment by pgamez** [comment] 2018-03-09 16:20
Thank you Jeff
Yes, actually today is the first time I am using enum datatypes... 
Indeed, my intention is to reference a datatype from an external file... This works for all datatypes (including variable length types) so, at the beginning I expected that the same procedure would work with enums too.
Since all the attributes of an enum datatype were the same (name, dtype and enum_dict) in both files, in my opinion it could be very useful that both enums were considered in fact the same "custom datatype" as well, and they could be cross-referenced. Especially when I need to copy some variables from one file into another with (a priori) unknown names, dimensions and types, inside a loop.

**Comment by pgamez** [comment] 2018-03-09 16:31
Umm... However, now after your fix regarding the "name" of the enum I think it can be done without cross-referencing

**Comment by jswhit** [comment] 2018-03-09 16:43
The problem is that for 'user defined data types'  (vlens, compound and enum types, but not vlen strings), a custom datatype is defined in the C library.  The cython type that refers to this custom datatype carries around a c pointer to pass to the library - if you try to use a datatype from another dataset (that hasn't been defined in the current dataset), the pointer is invalid.  That's why you get the 'not a valid data type' error.

**Comment by pgamez** [comment] 2018-03-09 18:42
Ok! I get it. Thank you very much for the fixing and the information. Cheers. Pedro

**Comment by jswhit** [comment] 2018-03-09 20:26
No problem. I merged the pull request, so closing now...

**Closed by jswhit** 2018-03-09 20:26 UTC
