### ISSUE TITLE
Slicing failing in last two releases

### ISSUE THREAD

**Issue by rmendels** [Unidata/netcdf4-python#928] opened 2019-05-11 01:22 UTC
The most version has broken some long-running code of mine (I am running version 1.5.1.2, obtained through condo-forge).  The code has been running fine for quite awhile..  What fails is something like this:

```python
junk = root.variables['junk']
junk[0, :] = junk1[:]
```

where junk is (15, 510) and junk1 is (510,).  Basically any kind of slicing where I am taking only a single coordinate in one of the dimensions fails.  Message is that the slices don't match in shape.  If however I first totally fill junk1 so that it it (15, 510) then:

```python
junk[:,  :]  = junk1[:, :]
```

works fine.  As I said this was working until very recently.  I don't update all the time so I don't know how many versions ago this started to fail,  but it is either a bug or a change in behavior of the package.  Are you requiring  np.transpose(junk1[:]) or junk1 to be (1, 510) or some such?  I can see the rational for that,  but the problem is it wasn't needed before.

**Comment by jswhit** [comment] 2019-05-11 02:46
Roy - this works for me with 1.5.1.2

```python
from netCDF4 import Dataset
import numpy as np
nc = Dataset('test.nc','w')
d1 = nc.createDimension('d1',15)
d2 = nc.createDimension('d2',150)
junk = nc.createVariable('junk',np.int,('d1','d2'))
junk1 = np.arange(150)
junk[0,:] = junk1
nc.close()
```

Does this not work for you, or am I getting it wrong?

**Comment by rmendels** [comment] 2019-05-11 02:51
@jswhit I can send you some files and the code that fails.  But they are at work,  on a computer I can't reach easily from home.  Will add Monday.  I don't think any of them are too big.  basically I updated yesterday and the code broke.

**Comment by jswhit** [comment] 2019-05-11 04:01
This bug was introduced in 1.5.1, but it should be fixed in 1.5.1.2.  Could be another corner case I missed though.  Please do attach the file to the ticket (gzipped tar files work).

**Comment by rmendels** [comment] 2019-05-11 16:07
@jswhit okay I VPN'ed in this morning and got the files.  So here goes. Let me know if the files don't come through
First:

conda list netcdf4
packages in environment at /Users/rmendels/anaconda3:



 Name                    Version                   Build  Channel
netcdf4                   1.5.1.2          py37h58b02fa_0    conda-forge

```python
from netCDF4 import Dataset, num2date, date2num
import numpy as np
import numpy.ma as ma
perp_npz = np.load('perp.2019.npz')
perp = perp_npz['perp']
myRound = np.sign(perp)*.5
perp1 = (perp + myRound).astype(int)
u_time = perp_npz['u_time']
root = Dataset('upwell_6hr.nc', 'a')
time = root.variables['time']
upwelling_index = root.variables['upwelling_index']
## next six lines show that the assignment works outside of netCDF
## for equivalent size array
time1 = time[:]
start_index = np.where(time1 == u_time[0])
start_index = int(start_index[0])
no_times = u_time.shape[0]
end_index = start_index + no_times + 1
time1[start_index:end_index] = u_time[:]
## next line shows same assignemnt failing to the file
time[start_index:end_index] = u_time[:]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "netCDF4/_netCDF4.pyx", line 4893, in netCDF4._netCDF4.Variable.__setitem__
  File "netCDF4/_netCDF4.pyx", line 5151, in netCDF4._netCDF4.Variable._put
IndexError: size of data array does not conform to slice
## next tow lines show that assignment works for equivalent array
## outside netCDF
junk = upwelling_index[:, :]
junk[:, start_index:end_index] = np.transpose(perp)
# next line shows same thing failing in the file
upwelling_index[:, start_index:end_index] = np.transpose(perp)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "netCDF4/_netCDF4.pyx", line 4893, in netCDF4._netCDF4.Variable.__setitem__
  File "netCDF4/_netCDF4.pyx", line 5151, in netCDF4._netCDF4.Variable._put
IndexError: size of data array does not conform to slice
```
[upwell_6hr.nc.zip](https://github.com/Unidata/netcdf4-python/files/3169242/upwell_6hr.nc.zip)

[perp.2019.npz.zip](https://github.com/Unidata/netcdf4-python/files/3169243/perp.2019.npz.zip)

**Comment by jswhit** [comment] 2019-05-11 17:20
I think the problem is that the slice `time[start_index:end_index]` has a length of 519, and extends past the end of the currently defined unlimited dimension by 1.  However, the array `u_time` has length 518.  netcdf4-python is now correctly (I believe) raising an error (at least since version 1.5.1).  In the line above, when you try the same operation on a numpy array (`time1[start_index:end_index]`) it works because numpy ignores the fact that end_index is past the end of the array and just interprets this slice as extending to the end of the array.  netcdf4-python can't do this, since `time` has an unlimited dimension - implying you want to extend the dimension by 1.

**Comment by jswhit** [comment] 2019-05-11 17:26
I think the fix is to replace

`end_index = start_index + no_times + 1`

with

`end_index = start_index + no_times`

**Comment by rmendels** [comment] 2019-05-11 17:38
@jswhit  

```python
u_time.shape
(518,)
 junk = time1[start_index:end_index]
junk.shape
(518,)
time1.shape
(76490,)
time.shape
(76490,)
junk[-1]
432630.0
time1[-1]
432630.0
```

Also the whole point of the code was adding new time periods.  So the code first would extend the time,  and then extend the data. I can extend the time but first extending time1 and then setting

```python
time[:] = time1[:]
```
 And your solution doesn't then say how I extend time.

 But as far as I can see, this has the data and time in the perp file within the existing bounds of the upwell_6hr.nc file.  In either case,  there was a change in behavior that broke code.

**Comment by jswhit** [comment] 2019-05-11 17:43
`end_index=76491` and `start_index=75972` so this implies a slice of length 519.  You get 518 when you use this slice on the array `time1` since it only has 76490 elements.  To extend the time array by 1 you specify the slice to extend past the end of the current unlimited dimension by 1, just like you are doing.  You have to assign an array of the right length to that slice, right now your `u_time` array is 1 short (it has length 518, needs to be 519).  
This did not raise an error before, that's true - but I'm not sure what it was doing.

**Comment by rmendels** [comment] 2019-05-12 17:18
You can close this

**Comment by jswhit** [comment] 2019-05-12 17:23
You can also leave off the 2nd index, and it will be inferred from the length of the array being assigned to the slice.  So, in this case

`time[start_index:] = u_time[:]`

will work, and will extend the time dimension if u_time is long enough.

**Closed by jswhit** 2019-05-12 17:23 UTC
