### ISSUE TITLE
Getting wrong value when netCDF4 python module is run over HPC

### ISSUE THREAD

**Issue by Tapas104** [Unidata/netcdf4-python#1111] opened 2021-06-07 11:17 UTC
I need to extract rainfall data from .nc4 file. I have used Dataset of netCDF4 module in python. I have extracted the data successfully in my local system. But when I run the same program in HPC I got different output.

I have installed the same version of netCDF4 in HPC home directory.

I am ready to provide any more information if required to answer the question. Thank you.

**Comment by jswhit** [comment] 2021-06-08 19:55
Ideally, a test program with sample data to reproduce the problem, plus information on library and python module versions installed on the HPC system (the checkversion.py script in the top level of the github repo can be used to get this info).

**Comment by jswhit** [comment] 2021-06-21 15:37
closing this issue due to a lack of actionable information.  @Tapas104 feel free to re-open when and if you can provide more information.

**Closed by jswhit** 2021-06-21 15:37 UTC
