### ISSUE TITLE
Round trip converts text attributes to strings

### ISSUE THREAD

**Issue by jjhelmus** [Unidata/netcdf4-python#529] opened 2016-02-18 21:12 UTC
When netcdf4-python is used to read a "text" attribute from a file and write that attribute to a second file the resulting attribute will be a string where-as the original attribute was "text".

For example:

``` Python
import netCDF4

# create a reference netCDF file with a text (non-unicode) attribute
ds1 = netCDF4.Dataset('test1.nc', 'w')
ds1.setncattr('foo', 'bar')
ds1.close()

# copy the attribute to a second file, result is a string attribute
ds1 = netCDF4.Dataset('test1.nc', 'r')
ds2 = netCDF4.Dataset('test2.nc', 'w')
ds2.setncattr('foo', ds1.getncattr('foo'))
ds1.close()
ds2.close()
```

ncdumps of the two files show that the text attribute was changed to a string attribute.

```
 ncdump test1.nc; ncdump test2.nc
netcdf test1 {

// global attributes:
		:foo = "bar" ;
}
netcdf test2 {

// global attributes:
		string :foo = "bar" ;
}
```

From what I can tell this is a result of #389 which addressed #388.  Unicode Python variables are written as string attributes (using nc_put_att_string) but reading a "text" or string attribute returns unicode.  One possible fix would be to have "text" attribute be returned as str (Python 2) or bytes (Python 3).

**Comment by jjhelmus** [comment] 2016-02-18 21:30
I think the issue is that both NC_CHAR and NC_STRING attribute types are decoded to unicode on [lines 1101-1121 of _netCDF4.pyx](https://github.com/Unidata/netcdf4-python/blob/master/netCDF4/_netCDF4.pyx#L1101-L1121).  I'm not sure what would happen if NC_CHAR attributes were not decoded on line 1113 but it might be an option.

**Comment by jswhit** [comment] 2016-02-18 22:22
I don't think there is any easy way to preserve the round-trip, especially with python 3, without adding significant complication and confusion.  Under what conditions would this actually be a problem?

**Comment by jjhelmus** [comment] 2016-02-18 22:35
The issues seems to be that other netcdf software does not support the "string" type qualifier on attributes.  In the case I ran into was that one of our users was having issues reading a file in Matlab after the "string" attribute modification were made (ARM-DOE/pyart#476).  A similar issue in xarray(pydata/xarray#681) has a bit more discussion and an alternative to try encoding all strings to ascii prior to writing the file.  

@shoyer or @jhamman might be able to provide more details on on this topic.

**Comment by jswhit** [comment] 2016-02-19 00:43
The trick suggested in pydata/xarray#681 could be used in your original example, i.e:

    import netCDF4
    def maybe_encode(string, encoding='ascii'):
        try:
            return string.encode(encoding)
        except UnicodeEncodeError:
            return string
    # create a reference netCDF file with a text (non-unicode) attribute
    ds1 = netCDF4.Dataset('test1.nc', 'w')
    ds1.setncattr('foo', 'bar')
    ds1.close()
    # copy the attribute to a second file, result is a string attribute
    ds1 = netCDF4.Dataset('test1.nc', 'r')
    ds2 = netCDF4.Dataset('test2.nc', 'w')
    ds2.setncattr('foo', maybe_encode(ds1.getncattr('foo')))
    ds1.close()
    ds2.close()

**Comment by jhamman** [comment] 2016-02-19 06:04
@jswhit - we we're going to take the `maybe_encode` route in `xarray`? Would you consider putting it in `netcdf4` instead? I don't have strong opinions but as far as I'm concerned, it only needs to go in one library.

**Comment by jswhit** [comment] 2016-02-19 13:36
If we do that, then all attributes that can be encoded as ascii will be returned as ascii text.  I'm not sure this is a good idea, but I'd like to hear opinions.

**Comment by jswhit** [comment] 2016-02-19 13:50
I spoke too soon - the solution is really pretty trivial (pull request #530).  If the attribute requested is of type ``NC_CHAR1``, the result is returned as an ascii (not unicode) string.

**Comment by jswhit** [comment] 2016-02-19 14:26
Note: to ensure that an attribute gets written as ascii (NC_CHAR), even with python3, use

    ds1.setncattr('foo', b'bar')

**Comment by jswhit** [comment] 2016-02-19 14:29
This example now works as expected in python 2 and 3:

    import netCDF4
    # create a reference netCDF file with a text (non-unicode) attribute
    ds1 = netCDF4.Dataset('test1.nc', 'w')
    ds1.setncattr('foo', b'bar')
    ds1.close()
    # copy the attribute to a second file, result is a string attribute
    ds1 = netCDF4.Dataset('test1.nc', 'r')
    ds2 = netCDF4.Dataset('test2.nc', 'w')
    ds2.setncattr('foo', ds1.getncattr('foo'))
    ds1.close()
    ds2.close()

A test is still needed for pull request #530.

**Comment by jswhit** [comment] 2016-02-19 16:56
This fix could break code that assumes that attributes are always returned as strings.  In python3, NC_CHAR attributes will now be returned as bytes.  This in fact broke some utility functions in netcdf4-python.

**Comment by jjhelmus** [comment] 2016-02-19 17:08
> This fix could break code that assumes that attributes are always returned as strings. In python3, NC_CHAR attributes will now be returned as bytes. This in fact broke some utility functions in netcdf4-python.

Agreed.  I think it Python 2 returning str objects when the attribute is stored as a NC_CHAR and unicode when stored as NC_STRING makes sense.  In Python 3 this gets a bit more difficult as both ascii and other unicode encoding should likely be returned as str as there is no unicode.  Return ascii as bytes in Python 3 will cause some issues since bytes behavior different than str (for examples "hello" + b" world" rasises an TypeError.

Perhaps another option is to have an toggle similar to set_auto_mask which controls how unicode is written in attributes. Maybe `set_char_attr_on` and `set_char_attr_off`? When on unicode objects will create NC_CHAR attributes.

**Comment by jjhelmus** [comment] 2016-02-19 17:30
Just tested one of the file with a NC_STRING type global attribute with Matlab 2011b.  I can confirm that at least this version of Matlab cannot read these attributes but can read NC_CHAR type attributes.

``` 
>> ncdisp('test.nc')
Source:
           /home/jhelmus/test.nc
Format:
           netcdf4
Global Attributes:
           foo1 = 'bar'
           foo2 = UNSUPPORTED DATATYPE

>> ncid = netcdf.open('test.nc', 'NOWRITE');
>> netcdf.getAtt(ncid,netcdf.getConstant('NC_GLOBAL'), 'foo2')
Error using netcdf.getAtt (line 64)
Attribute datatype 12 is not recognized.

>> netcdf.getAtt(ncid,netcdf.getConstant('NC_GLOBAL'), 'foo1')

ans =

bar
```

**Comment by jswhit** [comment] 2016-02-19 17:59
Returning NC_CHAR attributes as strings with python 3 will not fix your round-trip issue though.  I'm leaning towards keeping NC_CHAR attributes as bytes in python 3.  We could add an 'encoding' arg to getncattr that would convert to ascii on python 3.

**Comment by DennisHeimbigner** [comment] 2016-02-19 22:05
This may be just a noise comment, but remember how this is handled in C.
If the type of the attribute is char, then an array of characters is returned (which in c looks
like a non-null terminated string). This is true for netcdf-3 and netcdf-4.
If the type is string (netcdf-4 only) then a vector of strings is returned.
Technically, the charset in both cases is UTF-8, but for chars, this reduces to ascii
(the 8 bit  only subset of UTF-8). Of course people routinely cheat and include non-ascii characters
when they are really storing a string as an array of characters. They will often add the null termination
character as well.
So, out of curiosity, why does python not follow this convention also?

**Comment by jswhit** [comment] 2016-02-20 17:48
In python 3, there are ``byte`` and ``string`` objects.  A ``string`` is a collection of bytes, together with an encoding (``utf-8`` by default).    So, I think returning ``bytes`` when the attribute is ``NC_CHAR`` and a string when the attribute is ``NC_STRING`` is somewhat analagous to what the C library does.

**Comment by jswhit** [comment] 2016-02-23 18:30
@shoyer and @jhamman, are you OK with this approach?  If so, I will go ahead and merge.

**Comment by jswhit** [comment] 2016-02-24 22:41
pull request #530 has been merged, closing now...

**Comment by shoyer** [comment] 2016-02-24 23:27
Sorry, I'm just taking a look at this now. I think it's a mistake to return `bytes` on Python 3 when the attribute is `NC_CHAR`.

In my mind, `NC_CHAR` and `NC_STRING` match the Python 2 `str` and `unicode` types, respectively. So it's really a question of what it appropriate for Python 3.

Because Python 3 users still need to interact with netCDF3 files and netCDF4 files that use `NC_CHAR` to represent strings, decoding to the native Python 3 `str` type for attributes will generally be much more useful. Nobody wants to need to write code like `assert temperature.units == b'kelvin'`, or to need to pollute their code with utility functions like `_try_bytes_to_string`.

This will indeed mean we (still) can't faithfully roundtrip strings on Python 3. We'll either need to continue the current behavior (everything gets written as `NC_STRING`), or which to writing strings with all ASCII as `NC_CHAR` instead. This is a bit of a shame, but given the state of the broader netCDF4 ecosystem, I think we should prefer the second solution -- attempting to encode unicode strings as ASCII and saving them as `NC_CHAR`.

**Comment by jswhit** [comment] 2016-02-25 00:36
OK, clearly this needs more discussion. I reverted the merge, and reopened the ticket.

**Comment by jswhit** [comment] 2016-02-25 00:53
Now pull request #532 (branch new_issue529)

**Comment by jswhit** [comment] 2016-02-25 03:13
So, to summarize - there are several benefits to this change, and one big drawback

Pros:
* makes sense for Python 2 (NC_CHAR maps onto ``str``, NC_STRING to ``unicode``).
* preserves round-tripping of attribute types.
* is consistent with what h5py does (http://docs.h5py.org/en/latest/strings.html).
* in python 3, NC_CHAR should (technically) map to ``bytes``.

Con:
* most python 3 users would expect NC_CHAR attributes to behave like string objects, as they do in python 2 (and as they have done before this update).  

How about adding an 'encoding' keyword to the Dataset constructor? In python 3, if a file is opened with
    
    nc = Dataset('data.nc',encoding='ascii')

then when NC_CHAR attributes are read, they are encoded as ascii strings.  The default would be ``encoding=None`` which would cause NC_CHAR attributes to be returned as ``bytes``.   In python 2, the 'encoding' kwarg would be ignored.

**Comment by shoyer** [comment] 2016-02-25 04:42
If I understand correctly, HDF5 (and correspondingly, h5py) has had the string dtype since its inception. netCDF has not, so there are both loads of netCDF3 files out there were `NC_CHAR` is used to mean "string" and loads of programs that can't handle `NC_STRING`, even if they can otherwise handle netCDF4 (e.g., MATLAB as @jjhelmus mentioned earlier). Given these backwards compatibility constraints, I don't think it makes sense to take a strict approach of interpreting `NC_CHAR` as `bytes` on Python 3.

In an ideal world, we could have a new file format (e.g., netCDF5) which comes with string support from the start, and make a clean division for this new file format. Unfortunately, with netCDF we have a backwards compatible API, so I think we're pretty much stuck with the original "characters as strings". I don't see a way to transition away from this.

One way to reason about this is to imagine a world in which Python 2 and 3 are source compatible. You could write your own code in Python 3, but would have to interact with Python 2 only library. Would it really make sense to always interpret Python 2 strings as bytes when they're passed on to Python 3? That would be pretty maddening.

If we accept that bytes and strings are hopeless conflated in the netCDF world, we are indeed forced to make a choice of default interpretation/intent when loading data into Python 3. For attributes, I think it makes sense to interpret `NC_CHAR` as `str`, because attributes are intended for small, descriptive data. For arrays, `NC_CHAR` is still probably usually intended for strings, but these can be big enough data that the cost of decoding everything as unicode starts to be more questionable, so I think it's perfectly reasonable to keep these as a `bytes` dtype.

**Comment by jswhit** [comment] 2016-02-25 14:54
Regarding h5py, attributes are stored as

* Fixed-length ASCII (NumPy S type)
* Variable-length ASCII (Python 2 str, Python 3 bytes)
* Variable-length UTF-8 (Python 2 unicode, Python 3 str)

So, storing a python str attribute in python 2 will result in a byte string when read with python 3.
This is the behaviour that allows round-tripping.

**Comment by jswhit** [comment] 2016-02-25 15:39
@shoyer, regarding your comment about netCDF and backwards compatibility - I don't see this as a netCDF compatibility issue.  To me it's really a python 2 to 3 compatibility issue.  NC_CHAR maps well to python 2 str, but there is no corresponding ascii string data type in python 3, so we either have to interpret NC_CHAR as bytes or unicode.  There are tradeoffs either way.  If we interpret NC_CHAR as bytes, then client code has to deal with things like ``assert temperature.units == b'kelvin'``.  If we intrepret NC_CHAR as python 3 str (unicode), then we lose the ability to do round-trips, unless the client code explicit converts back to bytes before writing the attribute.  You are saying the latter behaviour is less bad, and you may be right.  I'm just not sure.

**Comment by shoyer** [comment] 2016-02-25 16:07
> If we intrepret NC_CHAR as python 3 str (unicode), then we lose the ability to do round-trips, unless the client code explicit converts back to bytes before writing the attribute. 

Yes, we would lose the ability to round-trip either bytes or strings on Python 3. But my preferred approach to coerce to NC_CHAR even when writing Python 3 strings, if possible, which would mean we lose the ability to round trip strings rather than bytes.

**Comment by jswhit** [comment] 2016-02-25 16:27
So you're suggesting we change the current behavior, and write all attributes as bytes (``NC_CHAR``) and then convert to ``str`` when they are read in?  Right now, we are writing bytes and python 2 ``str`` attributes as NC_CHAR, and all python 3 ``str`` attributes and python 2 ``unicode`` attributes as ``NC_STRING``.  

I guess in that case would try to guess whether a python 3 str is ascii, using try s.decode('ascii') and catch UnicodeDecodeError, or use the chardet module?  Sounds pretty dicey to me.

**Comment by shoyer** [comment] 2016-02-25 16:35
Yes, it does seem pretty dicey -- and a bit un-Pythonic, to be honest --
but I think it's the best of a bad set of options. Arguably, netCDF4-Python
should stick with something closer to the current behavior, leaving it to
the higher level libraries like xarray to pick a coercion strategy.

**Comment by jswhit** [comment] 2016-02-25 16:44
Given the pitfalls of both proposed changes 

1) converting NC_CHAR attributes to bytes on input in python 3
2) converting all attributes to NC_CHAR on output and back to strings on input.

I propose we leave the current behavior, which is

3)  convert all NC_CHAR (NC_STRING) to python str (unicode) on python 2, convert both NC_CHAR and NC_STRING to python str on python 3.  Write python str (unicode) as NC_CHAR (NC_STRING) on python 2 and write python str as NC_STRING on python 3.  

I'll leave this ticket open for further discussion - maybe I can be convinced that (1) or (2) is less bad than (3), or someone will come up with a better approach.

**Comment by dopplershift** [comment] 2016-02-25 16:50
(3) does sound like the best of a bad set of options to me.

I also wanted to clarify: "If I understand correctly, HDF5 (and correspondingly, h5py) has had the string dtype since its inception. "
- NetCDF3 is based on HDF4, no strings dtype only char
- NetCDF4 is based on HDF5, both strings and char dtypes

**Comment by jswhit** [comment] 2016-02-25 17:01
Regarding the original problem reported by @jjhelmus, the current workaround if you want to write an NC_CHAR attribute with python 3 is to do

    # nc is a Dataset object, att_string is a python 3 string.
    nc.foo = bytes(att_string)  # will write NC_CHAR
    #nc.foo = att_string # will write NC_STRING

**Comment by shoyer** [comment] 2016-02-25 17:16
@jswhit actually `nc.foo = bytes(att_string)  # will write NC_CHAR` doesn't work -- you need a `encoding='ascii'` in there. `nc.foo = att_string.encode('ascii')` would be the most succinct way to write that.

I agree that the current behavior is acceptable, though not entirely ideal given the poor netCDF4 support in tools like MATLAB or old versions of ncdump.

@dopplershift 

> NetCDF4 is based on HDF5, both strings and char dtypes

Yes, but because netCDF4 uses the same netCDF-C library as netCDF3, library maintainers need to update their code to support NC_STRING. This has been a slow process.

**Comment by DennisHeimbigner** [comment] 2016-02-25 17:22
My 2 cents:
The basic problem is that you made the choice to infer the attribute type
 from the value being assigned to the attribute. E.g. if I say
         var.attr = <some value>
then the type of var.attr is determined by the value's python type.
This appears to mean that you must have the same round trip problem for attribute of other types: if you assign, say, an integer to the attribute, then there is
no way to control the type to be, say, unsigned short.
It seems to me that you need to extend the api to expose attribute creation
in the same way that you expose variable creation so that a type can be specified.
Use of this form of attribute creation be optional and would be in addition to the existing assignment based creation. It would allow for proper typing if it was important to the file creator.
p.s. The unidata netcdf-3 format (as opposed to some other netcdf3 format)  is not based on HDF4; it is different file format.

**Comment by jswhit** [comment] 2016-02-25 17:27
@shoyer, does this not work for you? (a version of the original code provided by @jjhelmus)

    import netCDF4
    ds1 = netCDF4.Dataset('test1.nc', 'w')
    ds1.setncattr('foo', b'bar')
    ds1.close()
    ds1 = netCDF4.Dataset('test1.nc', 'r')
    ds2 = netCDF4.Dataset('test2.nc', 'w')
    ds2.setncattr('foo', bytes(ds1.getncattr('foo')))
    ds1.close()
    ds2.close()

ncdump should show:

    netcdf test1 {

    // global attributes:
	   	:foo = "bar" ;
    }

    netcdf test2 {

    // global attributes:
		    :foo = "bar" ;
    }

**Comment by jswhit** [comment] 2016-02-25 17:33
@DennisHeimbigner, we don't have that problem with numeric attributes.  The type is preserved.  For example,

    import netCDF4
    import numpy as np
    ds1 = netCDF4.Dataset('test1.nc', 'w')
    ds1.foo = np.array(42,dtype=np.int16)
    print type(ds1.foo)
    ds1.close()

gives

    <type 'numpy.int16'>

The problem is only with the ambiguity inherent in mapping NC_CHAR and NC_STRING to python types in python 3.

**Comment by jswhit** [comment] 2016-02-25 17:45
BTW:  Numpy follows the option (1) above (convert characters to bytes on python 3), namely

    from __future__ import print_function
    import numpy
    a = b'abc'
    aa = numpy.array(a)
    print(aa.dtype)
    b = 'abc'
    bb = numpy.array(b)
    print(bb.dtype)
    print(str(aa))
    print(str(bb))

produces

    |S3
    |S3
    abc
    abc

on python 2 and

    |S3
    <U3
    b'abc'
    abc

on python 3.  Following @DennisHeimbigner's train of thought, perhaps we should just return all attributes as numpy arrays (as we do for numeric attributes).

**Comment by DennisHeimbigner** [comment] 2016-02-25 19:31
Given you are already willing to do this:
    ds1.foo = np.array(42,dtype=np.int16)
Why are you averse to doing the same with strings when necessary?
You can still keep the direct assignment form and make its's semantics
be whatever you want.

**Comment by jswhit** [comment] 2016-02-25 20:12
If you want a 16 bit integer attribute, that's the only way to do it.  Most users would just do

    ds1.foo = 42

which would result in a 64-bit integer attribute (on a 64 bit system).

I'm not averse to users specifying what the type of the attribute will be, for example by doing

    ds1.foo = b'abc' # force NC_CHAR on python 3

but we also want to allow users to do
 
    ds1.foo = 'abc'

The problem is the latter will get translated to NC_CHAR on python 2 and NC_STRING on python 3 the way are doing it currently.  The OP noted that this can cause suprises.

**Comment by DennisHeimbigner** [comment] 2016-02-25 21:14
By what definition of surprise :-) 
Seriously, though. I know you have hashed out all the possibilities about. If you want "consistency",
then you have to translate ds1.foo = 'abc' to NC_CHAR under both python 2 and 3. Otherwise, IMO
you define the semantics using one of your solutions above and live with the consequences.

**Comment by jswhit** [comment] 2016-02-26 04:25
I implemented @shoyer's suggestion in pull request #533.  All attributes are written as NC_CHAR, unless they can't be decoded to ascii.  Here's an example:

    import netCDF4
    ds = netCDF4.Dataset('test.nc', 'w')
    ds.foo = u'caf\xe9'
    ds.bar = 'cafe'
    ds.close()

produces

    netcdf test {

    // global attributes:
	   	string :foo = "café" ;
	   	:bar = "cafe" ;
    }

with python 2 and python 3.

**Comment by jjhelmus** [comment] 2016-02-26 11:59
The proposed change in pull request #533 seems like a reasonable solution.  Although my original report was on round trip problems, the root of the issue was that I needed a method to reliably create netCDF files whose attributes were written as NC_CHAR and not NC_STRING.  As long as all the str/unicode used to set attributes can be encoded to ascii, the resulting file should not contain NC_STRING types which meets my needs.

I agree that this method does not allow a users to choose to write an ascii encodable str/unicode as NC_STRING but at least for me this is not a major concern.

**Comment by jswhit** [comment] 2016-02-26 17:10
How important is it to be able to specify that an attribute should be written as NC_STRING?  If there aren't users that require that, I'm in favor of merging pull request #533.

**Comment by dopplershift** [comment] 2016-02-26 17:43
I'd prefer there to be some way to for an NC_STRING, but it's not critical.

**Comment by jswhit** [comment] 2016-02-26 17:59
Here's a hackish workaround to force NC_STRING by adding a unicode blank at the end of an ascii string:


    import netCDF4
    nc = netCDF4.Dataset('test.nc','w',format='NETCDF4')
    nc.foo = u'foo' # will be written as NC_CHAR
    nc.bar = u'bar\u00a0' # append blank, will be written NC_STRING
    nc.close()

which produces

    netcdf test {

    // global attributes:
	    	:foo = "foo" ;
	    	string :bar = "bar " ;
    }

**Comment by jswhit** [comment] 2016-02-26 18:54
a ``setncattr_string`` method was added to ``Dataset`` and ``Variable`` in pull request #533.

**Comment by jswhit** [comment] 2016-02-28 15:26
@shoyer, does this look OK to you?  I'd like to merge pull request #533 soon if there are no objections/additional suggestions.

**Comment by jjhelmus** [comment] 2016-02-29 20:01
The functionality introduced by PR #533 looks good to me.

**Comment by jswhit** [comment] 2016-03-01 19:25
Pull request #533 merged.

**Closed by jswhit** 2016-03-01 19:25 UTC

**Comment by jhamman** [comment] 2016-03-01 19:32
Thanks @jswhit. This is great.
