### ISSUE TITLE
can't install under Ubuntu 15.04 / Debian 8

### ISSUE THREAD

**Issue by kain88-de** [Unidata/netcdf4-python#438] opened 2015-07-20 09:00 UTC
I'm trying to install netcdf4 with pip and the build step fails complaining that it can't find `H5public.h`

```
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include -I/home/malinke/.local/lib/python2.7/site-packages/numpy/core/include -I/usr/include/python2.7 -c netCDF4/_netCDF4.c -o build/temp.linux-x86_64-2.7/netCDF4/_netCDF4.o
    netCDF4/_netCDF4.c:273:22: fatal error: H5public.h: No such file or directory
     #include "H5public.h"
                          ^
```

I've installed the `libhdf5-dev` package and since I get to the compilation stage the setup.py seems to find the headers.  `dpkg` says that the headers are installed in `/usr/include/hdf5/serial`. This path it no passed correctly to the compiler which I assume is the reason it can't find the header. 

```
dpkg -L libhdf5-dev
/.
/usr
/usr/lib
/usr/lib/x86_64-linux-gnu
/usr/lib/x86_64-linux-gnu/hdf5
/usr/lib/x86_64-linux-gnu/hdf5/serial
/usr/lib/x86_64-linux-gnu/libhdf5_serial.settings
/usr/lib/x86_64-linux-gnu/libhdf5_serial_fortran.a
/usr/lib/x86_64-linux-gnu/libhdf5_cpp.a
/usr/lib/x86_64-linux-gnu/libhdf5_serialhl_fortran.a
/usr/lib/x86_64-linux-gnu/libhdf5_serial.a
/usr/lib/x86_64-linux-gnu/pkgconfig
/usr/lib/x86_64-linux-gnu/pkgconfig/hdf5-serial.pc
/usr/lib/x86_64-linux-gnu/libhdf5_hl_cpp.a
/usr/lib/x86_64-linux-gnu/libhdf5_serial_hl.a
/usr/include
/usr/include/hdf5
/usr/include/hdf5/serial
/usr/include/hdf5/serial/h5d.mod
/usr/include/hdf5/serial/H5CompType.h
/usr/include/hdf5/serial/hdf5.h
...
```

I'm running Ubuntu 15.04, libhdf5-dev is at version 1.8.13.

This might be a new change in Debian/Ubuntu.  Ubuntu 14.04 comes with libhdf5-dev version 1.8.11 which places the headers still at `/usr/include`

Can I pass the appropriate compiler flag to pip or does the setup.py need to be changed?

**Comment by jswhit** [comment] 2015-07-20 12:15
You can use setup.cfg or the `HDF5_INCDIR` environment variable to specify the directory explicity.

**Comment by kain88-de** [comment] 2015-07-20 12:56
Apparently not when `nc-config` is used. `nc-config --cflags` only returns `-I/usr/include -DgFortran` and the build process ignores every other variable set in `setup.cfg`. If I add `inc_dirs.append(HDF5_dir)` in setup.py line 240 the build works.

This will have worked before as long as the HDF5 headers where in `/usr/include` but now it is broken.

**Comment by jswhit** [comment] 2015-07-20 13:24
Right - you have to set `USE_NCCONFIG` to 0, and make sure setup.cfg does not exist if you want to specify the location of the headers and include files with env vars.

Alternately, you could just use setup.cfg and set use_ncconfig=False, then set the locations of the headers and libs manually.

**Comment by kain88-de** [comment] 2015-07-20 14:03
Yeah that should work. Though not really user friendly for people just wanting to install it via pip.

Would it be a viable solution for you to check of pkg-config is installed and has an entry for `hdf5` if nothing is provided for `HDF5_dir`?

**Comment by jswhit** [comment] 2015-07-21 00:39
Perhaps, but I don't know anything about pkg-config.  Seems like this is a consequence of a debian packaging bug - ``nc-config`` is reporting the wrong information.  Maybe you should file a bug report for the Ubuntu netcdf package?

**Comment by jswhit** [comment] 2015-07-21 00:43
see also issue #430

**Comment by jswhit** [comment] 2015-07-21 20:10
pull request #441 modifies setup.py to check USE_SETUPCFG env var. If it evaluates to False, setup.cfg will not be used.  In your case, this means that

``USE_SETUPCFG=0 HDF5_INCDIR=/usr/include/hdf5/serial pip install netCDF4``

should work.

I'd be oblidged if you could test this and make sure.

**Comment by jswhit** [comment] 2015-07-21 20:16
Forgot to mention that to test this you would need to do

``USE_SETUPCFG=0 HDF5_INCDIR=/usr/include/hdf5/serial pip install git+https://github.com/Unidata/netcdf4-python@setup``

**Comment by kain88-de** [comment] 2015-07-22 08:38
works using 

`USE_NCCONFIG=0 HDF5_INCDIR=/usr/include/hdf5/serial HDF5_LIBDIR=/usr/lib/x86_64-linux-gnu/hdf5/serial pip install --user git+https://github.com/Unidata/netcdf4-python@setup`

The first argument is due to a type in the PR and I also need to specify where the library is installed. Setting this to  `None` (not giving any option on the CLI) will result in a compilation error because `None` can't be added to strings.

**Comment by jswhit** [comment] 2015-07-22 12:21
Fixed the typo, thanks.  You are correct that if you specify HDF5_INCDIR you also need to specify HDF5_LIBDIR.  So, in your case

``USE_SETUPCFG=0 HDF5_INCDIR=/usr/include/hdf5/serial HDF5_LIBDIR=/usr/lib/x86_64-linux-gnu/hdf5/serial pip install --user git+https://github.com/Unidata/netcdf4-python@setup``

should now work.

**Comment by jswhit** [comment] 2015-07-22 12:43
The problem caused by ``None`` being added to lib_dirs when HDF5_LIBDIR is not specified is now fixed.

**Comment by kain88-de** [comment] 2015-07-22 12:49
works like a charm. Thanks

**Closed** 2015-08-04 20:17 UTC
