### ISSUE TITLE
netCDF4 1.4.2: unit test tst_dap.DapTestCase fails

### ISSUE THREAD

**Issue by bodgerer** [Unidata/netcdf4-python#856] opened 2018-11-02 16:48 UTC
Hi there,

Am trying to build netCDF4 1.4.2 from source and am running into a problem with the following unit test:

FAIL: runTest (tst_dap.DapTestCase)
testing access of data over http using opendap
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/somewhere/netCDF4-1.4.2/test/tst_dap.py", line 26, in runTest
    assert var.shape == varshape
AssertionError

Reading tst_dap.py, it's trying to download the following file, which doesn't seem to exist (getting an error code 400 when I try to download without netCDF4):

http://remotetest.unidata.ucar.edu/thredds/dodsC/testdods/testData.nc

Any ideas what's going on, please?

Thanks,

Mark

**Comment by jswhit** [comment] 2018-11-02 18:33
Their server must have been down when you ran the test.  Seems to be working now.  Set the env var NO_NET to disable the opendap test if you need the tests to pass.

**Comment by jswhit** [comment] 2018-11-02 18:48
BTW - you can't download the file directly from that link (you'll get a 404 error even when the server is working).

**Comment by bodgerer** [comment] 2018-11-07 11:51
Hi Jeff,

Thanks for this. Unless the site's down again, I think I still have a problem - see below for output of tests. The weird thing is that when I run the test individually ("python /somewhere/py/src/netCDF4-1.4.2/test/tst_dap.py"), it passes.

Adding a "print(var.shape)" reveals that var.shape = (1, 95, 135) as expected when the test is passed, but (0, 95, 135) when run from run_all.py. I'm using python 3.6.0.

Since the feature it's testing is clearly working, I can set NO_NET so that our automated processes work, but do you have any ideas why run_all.py fails, please?

```
$ python run_all.py
not running tst_unicode.py ...
not running tst_diskless.py ...

netcdf4-python version: 1.4.2
HDF5 lib version:       1.8.17
netcdf lib version:     4.4.1
numpy version           1.15.3
cython version          0.29
......................................................./somewhere/py/src/netCDF4-1.4.2/test/tst_types.py:92: UserWarning: WARNING: missing_value not used since it
cannot be safely cast to variable data type
  assert_array_equal(v3[:],-1*np.ones(n2dim,v3.dtype))
..................F.............................
======================================================================
FAIL: runTest (tst_dap.DapTestCase)
testing access of data over http using opendap
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/somewhere/py/src/netCDF4-1.4.2/test/tst_dap.py", line 26, in runTest
    assert var.shape == varshape
AssertionError

----------------------------------------------------------------------
Ran 103 tests in 64.298s

FAILED (failures=1)
```

**Comment by jswhit** [comment] 2018-11-07 13:34
Confirmed - the test (tst_dap.py) fails when run from run_all.py, but passes when run standalone.  For some reason, the record dimension shows up as length 0 instead of 1 when the test is run inside run_all.py.  Very weird.

**Comment by jswhit** [comment] 2018-11-07 13:46
Just changing the order the tests run seems to make it go away (try renaming tst_dap.py to tst_adap.py).  There must be some kind of interaction between the tests.

**Comment by jswhit** [comment] 2018-11-12 14:03
Pull request #857 seems to have fixed this, but it's a workaround and I would still like to understand the reason for the problem in the first place.

**Comment by jswhit** [comment] 2019-04-02 13:53
closing now

**Closed by jswhit** 2019-04-02 13:53 UTC
