### ISSUE TITLE
NetCDF: HDF error when Dataset(.., 'r+', format = 'NETCDF4') 

### ISSUE THREAD

**Issue by GUrbancic** [Unidata/netcdf4-python#737] opened 2017-11-02 09:14 UTC
Hello, 
I get the  error " OSError: NetCDF: HDF " when opening a NetCDF file, nc = Dataset( dir, 'r+', format = NETCDF4) but not when i only use "r" instead of "r+". 
Any ideas?
-G

**Comment by jswhit** [comment] 2017-11-02 12:23
Nope.  Can you post the file somewhere?

If it's small enough, you can zip it and attach to the ticket.

**Comment by jswhit** [comment] 2017-11-02 14:35
One thought - do you have write permissions to the directory that the file is in?

**Comment by jswhit** [comment] 2017-11-07 17:30
Was this a permissions issue?  Is it resolved?

**Comment by GUrbancic** [comment] 2017-11-07 21:36
My apologies for the late answer, the issue did get resolved. It was not a permissions issue, the code was quite long with one section only reading a NETCDF file and later on reopening the same file with r+. Once I removed this and just opened directly with r+ the problem went away.

**Comment by jswhit** [comment] 2017-11-08 17:11
so the error occurs when you open a file as 'r', then open the same file again as 'r+' without closing the first one?

**Comment by GUrbancic** [comment] 2017-11-08 17:50
That is correct.

**Comment by jswhit** [comment] 2017-11-08 18:36
Confirmed.  That's the error the library returns when you try to open a file with write access and it's already open read-only.  It would be nice to return a more informative error on the python side, but I don't see how I would trap it.

**Comment by akrherz** [comment] 2017-11-08 18:43
@GUrbancic's comment yesterday of 
> It was not a permissions issue, the code was quite long with one section only reading a NETCDF file and later on reopening the same file with r+

is a different issue it seems than what @jswhit just reproduced with
>  That's the error the library returns when you try to open a file with write access and it's already open read-only. 

for example
```python
import netCDF4

a = netCDF4.Dataset('test.nc', 'r')
b = netCDF4.Dataset('test.nc', 'r+')
```
results in
```
HDF5-DIAG: Error detected in HDF5 (1.8.18) thread 140285110429504:
  #000: H5F.c line 604 in H5Fopen(): unable to open file
    major: File accessibilty
    minor: Unable to open file
  #001: H5Fint.c line 1028 in H5F_open(): file is already open for read-only
    major: File accessibilty
    minor: Unable to open file
Traceback (most recent call last):
  File "a.py", line 4, in <module>
    b = netCDF4.Dataset('test.nc', 'r+')
  File "netCDF4/_netCDF4.pyx", line 2015, in netCDF4._netCDF4.Dataset.__init__
  File "netCDF4/_netCDF4.pyx", line 1636, in netCDF4._netCDF4._ensure_nc_success
IOError: [Errno -101] NetCDF: HDF error: 'test.nc'
```
additionally
```python
import netCDF4

a = netCDF4.Dataset('test.nc', 'r')
b = netCDF4.Dataset('test.nc', 'w')
```
results in
```
HDF5-DIAG: Error detected in HDF5 (1.8.18) thread 140062310770496:
  #000: H5F.c line 522 in H5Fcreate(): unable to create file
    major: File accessibilty
    minor: Unable to open file
  #001: H5Fint.c line 1024 in H5F_open(): unable to truncate a file which is already open
    major: File accessibilty
    minor: Unable to open file
Traceback (most recent call last):
  File "a.py", line 4, in <module>
    b = netCDF4.Dataset('test.nc', 'w')
  File "netCDF4/_netCDF4.pyx", line 2015, in netCDF4._netCDF4.Dataset.__init__
  File "netCDF4/_netCDF4.pyx", line 1636, in netCDF4._netCDF4._ensure_nc_success
IOError: [Errno 13] Permission denied: 'test.nc'
```

whereas

```python
import netCDF4

a = netCDF4.Dataset('test.nc', 'r')
b = netCDF4.Dataset('test.nc', 'r')
```
does not error out.

**Comment by jswhit** [comment] 2017-11-10 14:38
closing this, since it appears that it is actually expected behavior from the C lib

**Closed by jswhit** 2017-11-10 14:38 UTC
