### ISSUE TITLE
Inconsistent date2index

### ISSUE THREAD

**Issue by giovaniceotto** [Unidata/netcdf4-python#1155] opened 2022-02-27 03:46 UTC
# Description
The method `netCDF4.date2index` seems to be giving inconsistent results when using the `select=nearest` argument.
Using the file described above, here is an example:

```python
!pip install netCDF4==1.5.8
!wget https://github.com/Projeto-Jupiter/RocketPy/raw/master/tests/fixtures/acceptance/EPFL_Bella_Lui/bella_lui_weather_data_ERA5.nc

import netCDF4
from datetime import datetime

# Read weather file
weatherData = netCDF4.Dataset("bella_lui_weather_data_ERA5.nc")

# Get time, latitude and longitude data from file
timeArray = weatherData.variables['time']

date = datetime(2020, 2, 22, 13)

# Find time index
print(netCDF4.date2index(date, timeArray, calendar="gregorian", select="exact"))
print(netCDF4.date2index(date, timeArray, calendar="gregorian", select="before"))
print(netCDF4.date2index(date, timeArray, calendar="gregorian", select="after"))
print(netCDF4.date2index(date, timeArray, calendar="gregorian", select="nearest"))
```

**The expected output is that the last four lines should print the same thing, as long as the first of them does not result in a Value Error. However, this is the actual result, two different answers:**

```
>>> 3
>>> 3
>>> 3
>>> 2
```

Here is a [link to reproduce this in Colab](https://colab.research.google.com/drive/19bvecUCt-olZpzv9UkLN61I-q5bSNbVw?usp=sharing).

Is this really an issue or am I miss interpreting the behaviour of the `netCDF4.date2index` method?

# Environment Information
Python Version: 3.10
netCDF4 Version: 1.5.8
OS: Windows 11
Dataset File: [Bella Lui Weather Data - ERA3](https://github.com/Projeto-Jupiter/RocketPy/blob/master/tests/fixtures/acceptance/EPFL_Bella_Lui/bella_lui_weather_data_ERA5.nc)

**Comment by jswhit** [comment] 2022-02-28 01:21
date2index is actually part of [cftime](https://github.com/Unidata/cftime), so I'll create an issue there that links this one

**Comment by giovaniceotto** [comment] 2022-02-28 01:55
Thanks @jswhit, my mistake.

**Comment by jswhit** [comment] 2022-02-28 02:03
The index 3 is an exact match for the time requested, so 'exact' returns 3 (expected).  I think the issue is the 'before' and 'after' are really only relevant if there is an exact match.  From the docstring:

```
    **select**: **'exact', 'before', 'after', 'nearest'**
    The index selection method. `exact` will return the indices perfectly
    matching the times given. `before` and `after` will return the indices
    corresponding to the times just before or just after the given times **if
    an exact match cannot be found**. `nearest` will return the indices that
    correspond to the closest times.
```

**Comment by giovaniceotto** [comment] 2022-02-28 02:08
I expected that 'nearest' would return the exact one when it exists, and when it doesn't, it would return the same as after or before, whichever is closest.

However, as shown in my example, it can return something different from all the other options, which I do not understand.

**Comment by jswhit** [comment] 2022-02-28 02:17
Understood - I agree this is confusing and should be fixed.  From looking at the code all I can say at this point is that the 'nearest','before' and 'after' options probably only work as expected if there is not a perfect match to the time requested.

**Comment by jswhit** [comment] 2022-02-28 02:30
I've created a potential fix at https://github.com/Unidata/cftime/issues/272

**Comment by jswhit** [comment] 2022-03-01 02:12
this is now fixed in cftime

**Closed by jswhit** 2022-03-01 02:12 UTC
