### ISSUE TITLE
[RuntimeError: NetCDF: Not a valid ID] When subclassing netCDF4.Dataset

### ISSUE THREAD

**Issue by ElusiveTau** [Unidata/netcdf4-python#911] opened 2019-04-11 16:10 UTC
```
class CustomClassA(netCDF4.Dataset):
   def __init__(self, ncFilename):
       self.filename = ncFilename

if __name__ == '__main__':
    aCustomClassA = CustomClassA("testfile.nc")      # RuntimeError: NetCDF: Not a valid ID
```

**Comment by ElusiveTau** [comment] 2019-04-11 16:17
Here is the error message: 

_Traceback (most recent last call):
    File "RuntimeError.py", line 39, in <module>
        aCustomClassA = CustomClassA("testfile.nc")
    File "RuntimeError.py", line 12, in __init__
        self.filename = ncFilename
    File "netCDF\_netCDF4.pyx", line 2882, in netCDF4._netCDF4.Dataset.__setattr__
    File "netCDF\_netCDF4.pyx", line 2812, in netCDF4._netCDF4.Dataset.setncattr
    File "netCDF\_netCDF4.pyx", line 1538, in netCDF4._netCDF4.Dataset._set_att
    File "netCDF\_netCDF4.pyx", line 1469, in netCDF4._netCDF4.Dataset._get_format
    File "netCDF\_netCDF4.pyx", line 1857, in netCDF4._netCDF4.Dataset._ensure_nc_success
RuntimeError: NetCDF: Not a valid ID_

**Comment by dopplershift** [comment] 2019-04-11 20:29
I think your class is malformed. You need to be calling `__init__` for your parent class:
```python
class CustomClassA(netCDF4.Dataset):
   def __init__(self, ncFilename):
       super().__init__(ncFilename)
       self.filename = ncFilename

if __name__ == '__main__':
    aCustomClassA = CustomClassA("testfile.nc")
```

For me, this then errors because it assumes we're trying to open `testfile.nc` for reading, which is non-existant.

**Comment by jswhit** [comment] 2019-04-23 02:07
Closing this now, feel free to re-open if the issue is not resolved.

**Closed** 2019-04-23 03:19 UTC
