### ISSUE TITLE
bug: num2date(date2num(date)) roundtrip changes dates with year < 0

### ISSUE THREAD

**Issue by ckhroulev** [Unidata/netcdf4-python#596] opened 2016-10-25 04:53 UTC
Run this to reproduce:

``` python
import netcdftime

u = netcdftime.utime("seconds since 1-1-1", "julian")

date1 = netcdftime.datetime(-1, 1, 1)
date2 = u.num2date(u.date2num(date1))

print(date1)
print(date2)
```

`date1` should be equal to `date2`, but this script prints

```
  -1-01-01 00:00:00
  -2-01-01 00:00:00
```

(Tested using commit 8773adbcd324ae0cf2ba597d1d6d6b27bb28e649.)

**Comment by ckhroulev** [comment] 2016-10-25 04:55
This is one of the reasons why I decided not to use `date2num` and `num2date` to implement `datetime.__add__()` and `datetime.__sub__()`.

**Comment by ckhroulev** [comment] 2016-10-27 23:41
A related issue:

This code
``` python
import netcdftime
u = netcdftime.utime("seconds since 1-1-1", "proleptic_gregorian")
print(u.num2date(u.date2num(netcdftime.datetime(-1, 1, 1))))
```
attempts to create a `datetime.datetime` instance with the year of -1, which is not supported by `datetime`.

Here `num2date(date2num(date))` raises `ValueError` instead of evaluating to `date`.

(Tested using commit b3f12f8027ab898e7d5090db362f0783c4fa7980.)

**Comment by jswhit** [comment] 2016-10-31 21:04
I guess this is not related to pull request #586, since it happens with `proleptic_gregorian`.   I guess `date2num` should raise an error if a negative year is supplied and the calendar is not `360_day` or `365_day`?

**Comment by jswhit** [comment] 2016-11-04 16:57
Ignore my previous comment. I think the problem is that there is no year 0 in the Julian calendar, and date2num does not know this.

    import netcdftime
    from netCDF4 import date2num, num2date
    units = "days since 1-1-1"
    date1 = netcdftime.datetime(-1, 1, 1)
    t = date2num(date1,units)
    print t

gives

    -731

instead of 

    -366

**Comment by jswhit** [comment] 2016-11-04 17:38
fix is in pull request #598

**Comment by jswhit** [comment] 2016-11-04 17:58
I noticed that with the original example

    import netcdftime
    u = netcdftime.utime("seconds since 1-1-1", "julian")
    date1 = netcdftime.datetime(-1, 1, 1)
    date2 = u.num2date(u.date2num(date1))
    print date1,type(date1)
    print date2,type(date2)

now gives

     -1-01-01 00:00:00 <type 'netcdftime._netcdftime.DatetimeProlepticGregorian'>
     -1-01-01 00:00:00 <type 'netcdftime._netcdftime.DatetimeJulian'

why is the calendar type different?  This causes date1==date2 to thow the error

        date1 == date2
      File "netcdftime/_netcdftime.pyx", line 1285, in netcdftime._netcdftime.datetime.__richcmp__     (netcdftime/_netcdftime.c:20518)
    TypeError: cannot compare netcdftime._netcdftime.DatetimeProlepticGregorian(-1, 1, 1, 0, 0,    0, 0, -1, 1) and netcdftime._netcdftime.DatetimeJulian(-1, 1, 1, 0, 0, 0, 7, -1, 1) (different calendars)

**Comment by jswhit** [comment] 2016-11-04 18:01
of course, the above problem is avoided by using

    date1 = netcdftime.DatetimeJulian(-1,1,1)

**Comment by jswhit** [comment] 2016-11-07 15:39
merged pull request #598.  Still need to address the fact that `u.num2date` tries to create a datetime instance with a negative year in some cases.

**Comment by jswhit** [comment] 2016-11-07 16:07
pull request #600 fixes neg year issue in utime.num2date

**Comment by jswhit** [comment] 2016-11-07 20:27
pull request #600 merged, closing now

**Closed by jswhit** 2016-11-07 20:27 UTC
