### ISSUE TITLE
variable masked_array differences  between v1.4.1 and v1.4.2

### ISSUE THREAD

**Issue by RosalynHatcher** [Unidata/netcdf4-python#908] opened 2019-04-08 14:50 UTC
Hi,

I'm seeing a big difference in the way the same masked array is being handled between versions 1.4.1 and 1.4.2 (and newer).  I can't see anything in the changelog for v1.4.2 that explains this.  Could you please confirm that what I'm seeing is correct and intended?

netcdf4-python 1.4.1
```
>>> import netCDF4
>>> f=netCDF4.Dataset('CRM032_test1.nc')
>>> f.variables['rgrid'][:]
masked_array(data=[--, --, --, ..., --, --, --],
             mask=[ True,  True,  True, ...,  True,  True,  True],
       fill_value=-2147483647,
            dtype=int32)
>>> f.variables['rgrid'][:].count()
0
>>> f.variables['rgrid'][:].min()
masked
```

netcdf4-python 1.4.2 (and also tested with 1.5.0.1)
```
>>> import netCDF4
>>> f=netCDF4.Dataset('CRM032_test1.nc')
>>> f.variables['rgrid'][:]
masked_array(data=[-2147483647, -2147483647, -2147483647, ...,
                   -2147483647, -2147483647, -2147483647],
             mask=False,
       fill_value=999999,
            dtype=int32)
>>> f.variables['rgrid'][:].count()
10855
>>> f.variables['rgrid'][:].min()
-2147483647
>>> 
```

Here's the file that I'm using - containing header and no data.

```netcdf CRM032_test1 {
dimensions:
	longitude = 240 ;
	latitude = 61 ;
	rgrid = 10855 ;
	time = 1 ;
variables:
	float longitude(rgrid) ;
		longitude:units = "degrees_east" ;
	float latitude(rgrid) ;
		latitude:units = "degrees_north" ;
	int rgrid(rgrid) ;
		rgrid:compress = "latitude longitude" ;
		rgrid:standard_name = "atmosphere_cloud_condensed_water_content" ;
	int time(time) ;
		time:units = "days since 1961-01-01" ;
	float MSLP(time, rgrid) ;
		MSLP:standard_name = "atmosphere_cloud_condensed_water_content " ;
		MSLP:long_name = "MSLP Pressure" ;
		MSLP:units = "hPa" ;
		MSLP:cell_method = "time: mean" ;
		MSLP:grid_mapping = "rotated_stretched_latitude_longitude rotated_north_pole_latitude: 40. rotated_north_pole_longitude: 12. stretching_coefficient: 3" ;
		MSLP:coordinates = "longitude latitude" ;

// global attributes:
		:Conventions = "CF1.0" ;
		:source = "ARPEGE" ;
		:experiment = "DA9" ;
}
```

Thanks.
Regards,
Ros.

**Comment by jswhit** [comment] 2019-04-08 16:47
Can attach the file to the ticket  (as a zipped tar file)?

**Comment by RosalynHatcher** [comment] 2019-04-08 17:54
Yes, sorry - It's just the header above, my mac is not allowing me to attach tgz - but hopefully here it is masquerading as a text file!

[CRM032_test1.nc.tgz.txt](https://github.com/Unidata/netcdf4-python/files/3055633/CRM032_test1.nc.tgz.txt)

**Comment by jswhit** [comment] 2019-04-08 20:19
Hmmm.  When I open this file with 1.5.0.1 I see the expected result

```
masked_array(data=[--, --, --, ..., --, --, --],
             mask=[ True,  True,  True, ...,  True,  True,  True],
       fill_value=-2147483647,
            dtype=int32)
```

I notice in your case the masked array has a fill_value of 999999 - which explains why it does not have any masked values.  The default fill_value for integer variables is -2147483647.  I wonder if somehow your program is re-setting the _FillValue attribute to 999999?

**Comment by jswhit** [comment] 2019-04-08 20:22
It looks like the default numpy.ma fill value for int32 arrays is 999999 - so the question is why is the netcdf _FillValue not being used in your case.

**Comment by jswhit** [comment] 2019-04-08 20:23
What is your numpy version?

**Comment by RosalynHatcher** [comment] 2019-04-09 08:01
Thanks Jeff. 
The environment with netcdf4-python 1.4.1 is using numpy 1.14.3

netcdf4-python 1.4.2 (and 1.5.0.1) is using numpy 1.14.5

**Comment by RosalynHatcher** [comment] 2019-04-09 13:07
Hmmm - very odd; I'll try and do some more digging around this end.

**Comment by jswhit** [comment] 2019-04-09 16:11
I added your test to the test suite, and ran the regression tests on travis.  I am seeing some failures, so it's not just you!

**Comment by jswhit** [comment] 2019-04-09 16:24
Looks like the problem occurs with netcdf-c 4.4.0 and not with 4.6.x.  What version do you have installed?

**Comment by RosalynHatcher** [comment] 2019-04-09 16:50
Thanks for confirming I'm not going mad!  I've just run `ncdump -version` on both environments...

The configuration that "works"  with netcdf4-python 1.4.1 has netcdf-c 4.6.1

But the other server  (1.4.2) which is not very old is telling me it's netcdf-c 4.0.1 - that's absolutely ancient!! Can't believe that's the newest version we have on there.  Guess that would be the problem then?!

I'll speak to our sys admin and see if there is an newer version available/install a newer version and hopefully that will sort it out.  I'll run the test suite too.

**Comment by jswhit** [comment] 2019-04-09 17:02
Appears to be related to https://github.com/Unidata/netcdf-c/issues/379.  nc_inq_var_fill is returning a value of no_fill=1 for NETCDF3 files, which causes the python interface to assume that no fill values were written.  Looks like this was fixed by https://github.com/Unidata/netcdf-c/pull/383, which went into netcdf-c 4.5.1.

**Comment by jswhit** [comment] 2019-04-09 18:05
Pull request #909 implements a workaround for netcdf-c < 4.5.1.

**Comment by RosalynHatcher** [comment] 2019-04-10 09:47
Thanks very much for diagnosing and fixing this so quickly.  I confirm the workaround does as expected.

**Closed** 2019-04-10 12:18 UTC
