### ISSUE TITLE
get_variables_by_attributes not working on MFDataset

### ISSUE THREAD

**Issue by pgamez** [Unidata/netcdf4-python#610] opened 2016-12-05 08:27 UTC
Hello,

I noticed that `get_variables_by_attributes` does not work on MFDataset.
This script:
```python
#!/usr/bin/env python

import netCDF4 as nc

for i in range(2):
    with nc.Dataset('test-{}.nc'.format(i), 'w', format='NETCDF4_CLASSIC') as fp:
        fp.createDimension('time', None)
        time = fp.createVariable('time', 'i', ('time',))
        time.axis = 'T'
        time.units = 'days since 2001-01-01'
        time.calendar = 'standard'
        time[:] = i

with nc.MFDataset('test-*.nc') as fp:
    v = fp.get_variables_by_attributes(axis='T')
```
raises a TypeError:

```
Traceback (most recent call last):
  File "./test.py", line 15, in <module>
    v = fp.get_variables_by_attributes(axis='T')
  File "netCDF4/_netCDF4.pyx", line 2531, in netCDF4._netCDF4.Dataset.get_variables_by_attributes (netCDF4/_netCDF4.c:20697)
TypeError: 'NoneType' object is not iterable
```
Thank you

Pedro

**Comment by ocefpaf** [comment] 2016-12-05 14:18
Can you put together a [SSCCE](http://sscce.org/) with a small dataset so we can try to debug it?

**Comment by jswhit** [comment] 2016-12-05 20:40
`get_variables_by_attributes` is not implemented in MFDataset.

**Comment by ocefpaf** [comment] 2016-12-05 22:09
I probably missed that or assumed MFDataset inherited it. I'll take a look
and implement it soon

**Comment by pgamez** [comment] 2016-12-06 08:11
Hello Jeff and Filipe,
In my opinion it is a nice and useful method, and we will appreciate your future implementation for sure.
Many thanks!
Pedro

**Comment by jswhit** [comment] 2016-12-06 17:22
An alternate solution is in pull request #612.  The problem is that the method is inherited, but the `variables` attribute of the `Dataset` instance is not.  I'm not totally clear on why this is the case.  The solution in #612 is a hack - it checks to see if `variables` is `None`, and if it is, uses `_vars` instead, which is set by MFDataset.  This same solution is applied for the `Dataset.set_auto*` methods, so they don't have to be re-implemented in`MFDataset`.

**Comment by ocefpaf** [comment] 2016-12-06 17:23
> This same solution is applied for the Dataset.set_auto* methods, so they don't have to be re-implemented inMFDataset.

That is much better than #611

**Comment by jswhit** [comment] 2016-12-07 21:51
#612 merged, closing now.

**Closed** 2016-12-07 21:52 UTC
