### ISSUE TITLE
Vlen, scale_factor and least_significant_digit

### ISSUE THREAD

**Issue by cyrilleponcelet** [Unidata/netcdf4-python#1003] opened 2020-03-26 13:30 UTC
Hi everyones, 
I'm not sure if it is a bug or a netcdf limitation but I'm trying to create a vlen variable in conjonction with the use of scale factor or the use of the least_significant_digit in order to compress data.
For the least_significant_digit  I give an example of code I used to create the data, everything seems fine except that the data save to disk is still a float64 instead of an int32.

Is there a way to save in vlen array values that are seen like a float or double but stored as a different type ? I tryied to apply a scale_factor too without success.

* Version 1.5.3 
* Windows, anaconda, python 3.7

<pre>
`
import netCDF4 as nc
import tempfile as tmp
import numpy as np

""""
Create a vlen variable and try to apply least_significant_digit

"""
<pre>
file=tmp.mktemp(suffix=".nc")
with nc.Dataset(file,"w") as f:
        #create vlen type and name it
        vlen_t = f.createVLType(np.float, "my_type")
        x = f.createDimension("x",2)
        y = f.createDimension("y",3)
        vlvar = f.createVariable("var", vlen_t, ("y","x"),zlib = True, least_significant_digit =1)
        #fill with arbitrary values
        data = np.empty(len(y)*len(x),object)
        for n in range(len(y)*len(x)):
            #create array of variable len
            data[n] = np.pi+np.arange(2) #create fake data with pi values
        data = np.reshape(data,(len(y),len(x)))
        for y_i in range(0,len(y)):
            for x_i in range(0,len(x)):
                vlvar[y_i,x_i] = data[y_i,x_i] #we need to set value on by one otherwise numpy complains

def print_content_sample(file:str):
    with nc.Dataset(file) as input:
        values=input["var"]
        x_len=len(input.dimensions["x"])
        y_len=len(input.dimensions["y"])
        sample=values[1,1]
        last_index=len(sample)-1
        print(f"file {file} : content_vlen = [{sample[0]} ...{sample[last_index]} ]")

print_content_sample(file)
</pre>

`

**Comment by dopplershift** [comment] 2020-03-26 21:06
You're creating your Vlen type as a float--does changing that to int help?

**Comment by cyrilleponcelet** [comment] 2020-03-26 21:13
No, for least_significant_byte it tells me : 
`
 vlvar[y_i,x_i] = data[y_i,x_i]
  File "netCDF4\_netCDF4.pyx", line 4825, in netCDF4._netCDF4.Variable.__setitem__
  File "netCDF4\_netCDF4.pyx", line 4735, in netCDF4._netCDF4.Variable._assign_vlen
TypeError: wrong data type: should be int32, got float64

**Comment by cyrilleponcelet** [comment] 2020-03-27 14:45
Close by mistake

**Comment by jswhit** [comment] 2020-03-28 13:04
The `least_significant_digit` attribute is not used for vlen data types.  This should be mentioned in the docs.   Even if it where, it wouldn't change the data type from float to int (see http://unidata.github.io/netcdf4-python/netCDF4/index.html#section9).  `scale_factor` and `add_offset` are also ignored for vlen data types.  
I'm not sure that zlib compression does anything in the C lib for vlen data types either.

Perhaps you can explain what you are trying to achieve ?

**Comment by jswhit** [comment] 2020-03-28 13:06
From https://github.com/h5py/h5py/issues/156

"this behavior is caused by the way HDF5 stores VLEN data. The vlen "dataset" consists of pointers to a bunch of strings stored elsewhere in the file. Gzip dataset compression will compress the pointers but not the strings they point to."

(substitute 'float64 data' for 'strings')

**Comment by cyrilleponcelet** [comment] 2020-03-29 13:26
Hi, Thanks for the pointer to the HDF5 documentation.
What I'm trying to achieve is that in my case (underwater acoustic data) I got a 2D matrix of set of values (acoustic sample) stored as vlen since the number of sample varies everytimes. If not compressed this that lead to huge files, and my values are decimal values between -67.0 and 67.0 with 0.5 of precision
For sure compression does not works and I was looking at the least_significant_bit or scale factor method. They both work with classic values but not for vlen.

Ideally I would have like to store my samples as a byte value with a scale_factor, and when reading them they would have been returned as float values. (I do not mention anymore the least_significant_bit since it is more complicated to implements and has a lower compression rate in my case but the problem and conversion methods are the same).
 
For what I understand what is done with classical value is :
1) we declare a storage a byte for example and add a scale_factor attribute of type float
2) when giving netcdf api a float array, they are divided by the scale factor, casted to the destination type 
3) then is written to the netcdf file.

source : https://github.com/Unidata/netcdf4-python/blob/master/netCDF4/_netCDF4.pyx line 4900

When reading the code I can see that this is not done for vlen files, but I cannot see any reason why this should not be possible. Is there some limitation that I cannot see or it might become possible if anyone is willing to implement it ?

**Comment by jswhit** [comment] 2020-03-29 14:56
It should be possible - I will investigate.

Another potential solution would be to use the standard fixed-length variable time and set the length to the largest possible sample you might have.  If you only fill the values that you receive, and enable zlib compression (and possibly make the compression lossy use the `least_significant_digit` attribute) - the unused values should compress away to almost nothing.  I bet the files would be almost as small as if you used the vlen type, and reading/writing to the files would be much faster.

Here's an example of what I mean:

```python
from netCDF4 import Dataset
import numpy as np

# using vlens
nc = Dataset('test1.nc', 'w')
vlen_type = nc.createVLType(np.float64, 'vltest')
nc.createDimension('x', None)
v = nc.createVariable('vl', vlen_type, 'x')
# random lengths between 1 and 1000
ilen = np.random.randint(1,1000,size=100)
n = 0
for nlen in ilen:
    data = np.random.uniform(low=0.0, high=1.0, size=nlen)
    v[n] = data
    n += 1
nc.close()

# using fixed size arrays with lossy compression
nc = Dataset('test2.nc', 'w')
nc.createDimension('x', None)
nc.createDimension('y', 1000) # max possible size of data
v = nc.createVariable('fl', np.float64, ('x','y'), zlib=True,
        least_significant_digit=1)
# random lengths between 1 and 1000
        least_significant_digit=1)
# random lengths between 1 and 1000
ilen = np.random.randint(1,1000,size=100)
n = 0
for nlen in ilen:
    data = np.random.uniform(low=0.0, high=1.0, size=nlen)
    v[n,0:nlen] = data[:]
    n += 1
nc.close()
```

file test2.nc ends up being nearly 10 times smaller than test1.nc.

**Comment by cyrilleponcelet** [comment] 2020-03-29 20:00
Thanks for your comments and code.
I modified it in order to have random lenght between 900 and 1000 and activate compression with the scale factor values.
The effect of compression is really impressive and its cost in time is very low (I made some benchmark a few years ago and I didn't remember that the times were so good). 

Unfortunately the use of vlen is written in a convention (Sonar-Netcdf)  and people have agreed to work with this type of data. Even if performance are less good they have judged it more elegant. (Otherwise they should have add next to the vlen data another variable giving the number of values to be able to know how many samples were recorded).

Another point I see is that if one of the value has a huge number of records then the matrix used to store it will have this size. That's ok for file storage with what you told but when loading the data we will allocate all the size of the matrix even if it is completely sparse. The vlen allow us to work x value per x value and retrieve only the needed amount of data. But I agree this can be done to with another variable giving the number of records effectively written.

You're probably right as a matter of size and time, it is probably better to work with fixed lenght matrix. But I'm stuck with the vlen and was really hoping that scale_factor could have work with vlen at least to save some space.

Note : another use case I just think about, in some case file is written on the fly and we never know in advance the number of samples.

**Comment by jswhit** [comment] 2020-03-29 22:35
You can try PR #1004 by checking out the `issue1003` branch.  Here's the simple example I used to test:

```python
from netCDF4 import Dataset
import numpy as np
nc = Dataset('test3.nc', 'w')
vlen_type = nc.createVLType(np.uint8, 'vltest')
nc.createDimension('x', None)
v = nc.createVariable('vl', vlen_type, 'x')
v.scale_factor = 1./255.
# random lengths between 1 and 1000
ilen = np.random.randint(1,1000,size=100)
n = 0
for nlen in ilen:
    data = np.random.uniform(low=0.0, high=1.0, size=nlen)
    if n==0:
        # mark last value as missing
        mask = np.zeros(data.shape,dtype=bool)
        mask[-1]=True
        data = np.ma.masked_array(data, mask=mask)
    if n==0: print(data)
    v[n] = data
    n += 1
print
print(v[0])
nc.close()
```

**Comment by cyrilleponcelet** [comment] 2020-03-30 15:34
I made a few checks and this is very good, everything seems OK to me.
I checked with set_auto_maskandscale and it works well, I check with missing_value attribute, it works too. 
Everything is perfect

**Comment by jswhit** [comment] 2020-03-30 20:35
OK, glad to hear it.  I'm going to merge PR #1004 and close this now.  Feel free to reopen it if you find any issues.

**Closed by jswhit** 2020-03-30 20:35 UTC
