### ISSUE TITLE
array reading issue for data with fill value

### ISSUE THREAD

**Issue by christine-e-smit** [Unidata/netcdf4-python#515] opened 2016-01-25 14:59 UTC
I am seeing behavior that does not make sense to me when I read a simple netcdf file in python. Here is my input netcdf file:

netcdf file {
dimensions:
time = UNLIMITED ; // (1 currently)
variables:
int time(time) ;
time:standard_name = "time" ;
time:units = "seconds since 1970-01-01 00:00:00" ;
float var(time) ;
var:_FillValue = -9999.f ;

// global attributes:
:Conventions = "CF-1.4" ;
data:

 time = 1230940800 ;

 var = _ ;
}

Note that 'var' has a single element, which is the fill value. I expect that I should be able to access this single element of the 'var' array in two different ways: (1) I can get out the entire data array and then access the first value or (2) I can directly get the first value out of 'var'. I expect that I should get exactly the same result either way, but I don't! This code prints out two different statements:

```python
from netCDF4 import Dataset
import numpy as np

nc = Dataset("/home/csmit/temp/file.nc")
vardata = nc["var"][:]
# prints out "First element is masked!"
if vardata[0] is np.ma.masked:
    print "First element is masked!"
else:
    print "First element is not masked."

firstElement = nc["var"][0]
# prints out "First element is not masked."
if firstElement is np.ma.masked:
    print "First element is masked!"
else:
    print "First element is not masked."
```

The first 'if' statement prints out 'First element is masked!' but the second 'if' statement prints out 'First element is not masked.' When my input file has a single float value, I seem to get the same float value regardless of how I access it. So I think something strange is going on with this fill value.

**Comment by jswhit** [comment] 2016-01-25 16:05
Can't reproduce this with github master.  Here's my test script

    from netCDF4 import Dataset
    import numpy as np
    nc = Dataset('test.nc','w')
    d = nc.createDimension('x',1)
    v = nc.createVariable('v',np.float,'x',fill_value=-9999)
    nc.close()
    nc = Dataset('test.nc')
    print nc['v'][:]
    print nc['v'][0]

which prints

    [--]
    --

what version of netcdf4-python are you using?

**Comment by jswhit** [comment] 2016-01-25 16:17
OK, I think I see what is going on.  ``nc['v'][:][0]`` returns a ``<class 'numpy.ma.core.MaskedConstant'>``, which evaluates as ``True`` when compared to ``np.ma.masked``.  However, ``nc['v'][0]`` returns a scalar ``<class 'numpy.ma.core.MaskedArray'>``, which does not.  

However, ``nc['v'][:][0].mask`` and ``nc['v'][0].mask`` both evaluate as True.

**Comment by christine-e-smit** [comment] 2016-01-25 16:29
But there is something strange going on here. Using your example, here is what I have in ipython using your example:

```
In [36]: nc['v'][:][0]
Out[36]: masked

In [37]: nc['v'][0]
Out[37]: 
masked_array(data = --,
             mask = True,
       fill_value = -9999.0)

In [38]: nc['v'][0].shape
Out[38]: ()
```
So basically, `nc['v'][:][0]` is numpy.ma.masked (looks good to me!) , but `nc['v'][0]` is a masked array with no elements (seems odd).

**Comment by jswhit** [comment] 2016-01-25 17:35
It's a numpy scalar array (http://docs.scipy.org/doc/numpy-1.10.0/reference/arrays.scalars.html), which is the expected result of a slice that returns a single element.

**Comment by christine-e-smit** [comment] 2016-01-25 17:52
I'm afraid I'm still not following the logic. I think you are saying that `nc['v'][0]` returns a numpy scalar array because the `[0]` is a slice. By that logic, isn't `nc['v'][:][0]` also a slice of the numpy array `nc['v'][:]` and shouldn't it then also return a slice?

**Comment by christine-e-smit** [comment] 2016-01-25 18:07
The documentation is not 100% clear, but it looks to me as though numpy treats single element indexing differently from other slices:

http://docs.scipy.org/doc/numpy-1.10.1/user/basics.indexing.html

In the case of a single element, it just returns the element rather than a new array. That's certainly what it looks like when I play around with a numpy array, anyway:
```
In [1]: import numpy as np

In [2]: arr = np.array([0.0,1.0])

In [3]: arr
Out[3]: array([ 0.,  1.])

In [4]: arr[0]
Out[4]: 0.0

In [5]: arr[0:1]
Out[5]: array([ 0.])

```

**Comment by jswhit** [comment] 2016-01-25 18:30
I know it's confusing - we tried to make the behaviour of netCDF variables similar to numpy arrays, with regards to slicing.  It seems to me that what your are seeing *is* consistent with what you would expect from a numpy array.

**Comment by christine-e-smit** [comment] 2016-01-25 19:18
But it's *not* consistent with numpy. That's what I'm saying. If you use single indexing on a numpy array (`arr[0]`), you get a scalar back, not an array. If you use slicing on a numpy array and that slice happens to return a single element (`arr[0:1]`), you get back and array that is of size (1,). So how is Variable's indexing consistent with numpy?

Variable is not even self-consistent. Let me expand your example to include another variable that actually has a value:

```python
from netCDF4 import Dataset
import numpy as np
nc = Dataset('test.nc','w')
d = nc.createDimension('x',1)
v = nc.createVariable('v',np.float,'x',fill_value=-9999)
v2 = nc.createVariable('v2',np.float,'x',fill_value=-9999)
v2[0] = 1.0
nc.close()
nc = Dataset('test.nc')
print "v: single element, masked "
print type(nc['v'][0])
print type(nc['v'][0:1])
print "v2: single element, not masked "
print type(nc['v2'][0])
print type(nc['v2'][0:1])

```

For me, this outputs:

```
v: single element, masked 
<class 'numpy.ma.core.MaskedArray'>
<class 'numpy.ma.core.MaskedArray'>
v2: single element, not masked 
<type 'numpy.float64'>
<type 'numpy.ndarray'>

```
Note when the single value is masked, both single indexing (`[0]`) and slicing to get a single element (`[0:1]`) return an array. In contrast, when the single value is *not* masked, single indexing returns a numpy.float64 and slicing to get a single element returns an array. For consistency, Variable should either *always* return an array for single indexing or *never* return an array for single indexing.

**Comment by jswhit** [comment] 2016-01-25 19:46
I guess I'm confused.  I still think netcdf4-python is doing the same thing as numpy, but maybe I haven't taken the time to think this through carefully enough.  For example:

    >>> from numpy import *
    >>> a = array([1.0])
    >>> type(a[0])
    <type 'numpy.float64'>
    >>> type(a[0:1])
<type 'numpy.ndarray'>

Slicing the numpy array with [0:1] returns a single element array.  Slicing with [0] returns a numpy scalar.

**Comment by jswhit** [comment] 2016-01-25 19:52
OK I get it - I typed too fast.  You are saying that slicing a single element netcdf variable which is masked returns a masked array not a masked scalar.  This probably is a bug.

**Comment by christine-e-smit** [comment] 2016-01-25 22:32
Cool! Sorry I wasn't clear the first time.

**Comment by jswhit** [comment] 2016-01-26 00:22
Well, I'm still confused.  netcdf4-python ``nc['v'][:][0]`` returns a ``MaskedConstant`` and ``nc['v'][0]`` returns a scalar masked array (an array with no shape).  Admittedly, I don't understand the distinction between the two, but it's not obvious to me what the 'right' or 'expected' answer is.

**Comment by christine-e-smit** [comment] 2016-01-26 16:07
For masked array, `ma.masked`, which is of type `MaskedConstant` is a placed holder for masked data. It is how you are supposed to (1) check to see if a particular element is masked and (2) set the mask for a particular element:

http://docs.scipy.org/doc/numpy/reference/maskedarray.baseclass.html

E.g. -
Create a simple masked array, where the second element is masked. Check to see if that element is masked:

```python
In [1]: import numpy.ma as ma

In [2]: x = ma.array([1,2,3],mask=[False,True,False])

In [3]: x[1] is ma.masked
Out[3]: True

In [4]: type(x[1])
Out[4]: numpy.ma.core.MaskedConstant

In [5]: x[1]
Out[5]: masked
```
In contrast, try `x[1:1]`, which produces a zero-sized masked array. Now the test does not work:
```
In [6]: x[1:1] is ma.masked
Out[6]: False

In [7]: type(x[1:1])
Out[7]: numpy.ma.core.MaskedArray

In [8]: x[1:1]
Out[8]: 
masked_array(data = [],
             mask = [],
       fill_value = 999999)
```

**Comment by christine-e-smit** [comment] 2016-01-26 16:13
So, if we use your example again:

```python
n [1]: from netCDF4 import Dataset

In [2]: import numpy as np

In [3]: nc = Dataset('test.nc','w')

In [4]: d = nc.createDimension('x',1)

In [5]: v = nc.createVariable('v',np.float,'x',fill_value=-9999)

In [6]: nc.close()

In [7]: nc = Dataset('test.nc')
```
Check to see if that one and only element is masked with `nc['v'][0]`:
```
In [8]: nc['v'][0] is np.ma.masked
Out[8]: False
```
and we do not get the `numpy.ma.MaskedArray` class behavior. But if we get out the entire array as a masked array (`nc['v'][:]`) and then index:
```
In [9]: nc['v'][:][0] is np.ma.masked
Out[9]: True
```
Now I get the standard masked array behavior.

**Comment by jswhit** [comment] 2016-01-26 17:41
OK, I've created a pull request that should take care of this (pull request #516).  Can you give it a try?

**Comment by christine-e-smit** [comment] 2016-01-26 19:23
Works beautifully! Just what I was expected to see. Thank you!!

**Comment by jswhit** [comment] 2016-01-26 22:20
Good.  Pull request #516 merged, closing now...

**Closed by jswhit** 2016-01-26 22:20 UTC

**Comment by lukecampbell** [comment] 2016-05-10 18:18
Just in case anyone comes across this issue in the future. Before the interface could be used like this:

```
>>> from netCDF4 import Dataset
>>> nc = Dataset(path)
>>> nc.variables['sea_water_temperature'][-1].item()
-9999.0
>>> nc.variables['sea_water_temperature'][-1].item() == nc.variables['sea_water_temperature']._FillValue
True
```

But now you MUST use a slice to get the same behavior as before:

```
>>> from netCDF4 import Dataset
>>> nc = Dataset('http://data.oceansmap.com/thredds/dodsC/ndbc_agg/44065/44065.ncml')
>>> nc.variables['sea_water_temperature'][-1].item()
0.0
>>> nc.variables['sea_water_temperature'][-1].item() == nc.variables['sea_water_temperature']._FillValue
False
>>> nc.variables['sea_water_temperature'][-1:].item()
-9999.0
```
